package web

import (
	"context"
	"fmt"
	"log"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/kivali-ai/kivali/internal/agent"
	"github.com/kivali-ai/kivali/internal/provider"
	"github.com/kivali-ai/kivali/internal/store"
)

// Episode-writer tuning.
//
// The writer digests one archived chat generation into
// chats/<ts>/episode.md — the immutable "what happened" record the
// agent greps through /files/episodes/. It runs on core, off the
// rotation's critical path, so a pod eviction mid-rotation loses
// nothing (the archive is already on disk) and the prompt can be
// improved and the corpus regenerated by deleting the files.
//
// inputCharCap: the rendered transcript Haiku sees. Long chats are
// shortened at message boundaries, keeping the opening (what was
// asked) and favouring the end (what was concluded) — see
// renderEpisodeTranscript.
//
// retryDelay: how long the writer waits before re-sweeping after a
// failed call. Nothing else re-kicks a failed generation — the
// rotation notified once — so without the sweep one transient error
// would leave a gap in episodes/ until the next boot.
const (
	episodeMaxTokens        = 1500
	episodeTimeout          = 120 * time.Second
	episodeRetryDelay       = 60 * time.Second
	episodeInputCharCap     = 80_000
	episodeToolExcerptChars = 400
	// episodeQueueDepth bounds NotifyEpisode's buffer. A full buffer
	// drops the notification, and the retry sweep (and every boot)
	// rescans for gaps — so a drop costs latency, never the episode.
	episodeQueueDepth = 64
)

// episodeRequest names one archived generation to digest.
type episodeRequest struct {
	slug string
	ts   string
}

// NotifyEpisode asks the writer to digest generation ts of slug.
// Non-blocking; safe from any goroutine. No-op when the writer isn't
// running (Claude backend unconfigured).
func (s *Server) NotifyEpisode(slug, ts string) {
	if s.episodeCh == nil || s.Claude == nil {
		return
	}
	select {
	case s.episodeCh <- episodeRequest{slug: slug, ts: ts}:
	default:
		log.Printf("episode %s/%s: writer queue full; the next sweep will pick it up", slug, ts)
	}
}

// runEpisodeWriter is the digest loop. Started once per server (when
// Claude is configured); lives for the process lifetime.
//
// Boot sweep first: every active agent's generations without an
// episode, oldest first. That sweep IS the production backfill — a
// deploy that introduces episodes digests the existing archive by
// itself, resumes across restarts (each write is idempotent and each
// sweep starts from whatever is still missing), and runs the same
// code path as steady state. Then one digest per rotation notification,
// with a retry sweep armed whenever a call fails.
func (s *Server) runEpisodeWriter() {
	timer := s.clk().NewTimer(episodeRetryDelay)
	if !s.sweepMissingEpisodes() {
		timer.Stop()
	}
	for {
		select {
		case req := <-s.episodeCh:
			wrote, err := s.writeEpisode(req.slug, req.ts)
			if err != nil {
				log.Printf("episode %s/%s: %v", req.slug, req.ts, err)
				timer.Reset(episodeRetryDelay)
				continue
			}
			if wrote {
				s.linkEpisodes(req.slug)
			}
		case <-timer.C():
			if s.sweepMissingEpisodes() {
				timer.Reset(episodeRetryDelay)
			}
		}
	}
}

// sweepMissingEpisodes digests every generation of every active agent
// that has no episode yet, oldest first. Returns true when something
// failed and the caller should arm a retry. One agent's failure never
// stops another's backfill.
func (s *Server) sweepMissingEpisodes() (retry bool) {
	agents, err := s.Store.ListActiveAgents()
	if err != nil {
		log.Printf("episode sweep: list agents: %v", err)
		return true
	}
	for _, a := range agents {
		missing, err := s.Store.ListArchivedChatsWithoutEpisode(a.Slug)
		if err != nil {
			log.Printf("episode sweep %s: %v", a.Slug, err)
			retry = true
			continue
		}
		wroteAny := false
		for _, m := range missing {
			wrote, err := s.writeEpisode(a.Slug, m.Timestamp)
			if err != nil {
				log.Printf("episode %s/%s: %v", a.Slug, m.Timestamp, err)
				retry = true
				continue
			}
			wroteAny = wroteAny || wrote
		}
		if wroteAny {
			s.linkEpisodes(a.Slug)
		}
	}
	return retry
}

// writeEpisode digests one generation. Returns wrote=false without
// error when there is nothing to do: the episode already exists, or
// the transcript is empty. The agent-visible symlink is the caller's
// job (linkEpisodes), so a backfill sweep links once per agent rather
// than once per generation.
func (s *Server) writeEpisode(slug, ts string) (wrote bool, err error) {
	if s.Store.HasEpisode(slug, ts) {
		return false, nil
	}
	msgs, err := s.Store.ReadArchivedChat(slug, ts)
	if err != nil {
		return false, fmt.Errorf("read archive: %w", err)
	}
	if len(msgs) == 0 {
		return false, nil
	}
	ctx, cancel := context.WithTimeout(context.Background(), episodeTimeout)
	defer cancel()
	ep, err := s.callEpisode(ctx, msgs)
	if err != nil {
		return false, err
	}
	if ep.title == "" {
		ep.title = fallbackEpisodeTitle(msgs, ts)
	}
	if err := s.Store.WriteEpisode(slug, ts, renderEpisodeFile(ts, ep)); err != nil {
		return false, fmt.Errorf("write: %w", err)
	}
	return true, nil
}

// linkEpisodes refreshes the agent's /files/episodes/ farm so a digest
// written moments ago is readable on the agent's very next turn: this
// is the farm's edge (store.SyncAgentFilesystem lists them all). A
// failure is logged; the next sync of the agent (a rotation, a
// restart) links it.
func (s *Server) linkEpisodes(slug string) {
	if err := s.Store.SyncAgentFilesystem(slug); err != nil {
		log.Printf("episode %s: files sync: %v", slug, err)
	}
}

// episode is the parsed model output: the two frontmatter fields the
// search relies on plus the digest body.
type episode struct {
	title   string
	touched string
	body    string
}

// callEpisode is the Haiku call, extracted so the eval harness can
// exercise the prompt against fixtures without a Server.
func (s *Server) callEpisode(ctx context.Context, msgs []store.ChatMessage) (episode, error) {
	if s.Claude == nil {
		return episode{}, fmt.Errorf("claude backend not configured")
	}
	return callEpisodeWith(ctx, s.Claude, s.SummaryModel, msgs)
}

func callEpisodeWith(ctx context.Context, c provider.Client, model string, msgs []store.ChatMessage) (episode, error) {
	req := provider.CompleteRequest{
		Model:     model,
		MaxTokens: episodeMaxTokens,
		Purpose:   "episode",
		System: []provider.SystemBlock{
			{Text: episodePromptSystem},
		},
		Messages: []provider.Message{
			{
				Role:    provider.RoleUser,
				Content: []provider.ContentBlock{{Type: provider.ContentText, Text: renderEpisodeTranscript(msgs)}},
			},
		},
	}
	resp, err := c.Complete(ctx, req)
	if err != nil {
		return episode{}, err
	}
	text := strings.TrimSpace(flattenTextContent(resp.Content))
	if text == "" {
		return episode{}, fmt.Errorf("model returned no text")
	}
	return parseEpisode(text), nil
}

// parseEpisode splits the model's reply into frontmatter fields and
// body. Tolerant: a reply with no "---" separator becomes an untitled
// body (writeEpisode then falls back to the transcript's opening
// line), so a model that drifts from the format degrades to a weaker
// title rather than to a gap that retries forever.
func parseEpisode(text string) episode {
	var ep episode
	head, body, found := strings.Cut(text, "\n---\n")
	if !found {
		ep.body = strings.TrimSpace(text)
		return ep
	}
	for _, line := range strings.Split(head, "\n") {
		key, val, ok := strings.Cut(line, ":")
		if !ok {
			continue
		}
		val = strings.TrimSpace(val)
		switch strings.ToLower(strings.TrimSpace(key)) {
		case "title":
			ep.title = strings.Trim(val, `"'`)
		case "touched":
			ep.touched = val
		}
	}
	ep.body = strings.TrimSpace(body)
	return ep
}

// renderEpisodeFile is the on-disk shape: frontmatter carrying the
// three fields the search relies on (ts is the id the semantic tier
// cites; title and touched are what a grep hits), then the digest.
func renderEpisodeFile(ts string, ep episode) string {
	touched := strings.TrimSpace(ep.touched)
	if touched == "" {
		touched = "-"
	}
	var b strings.Builder
	b.WriteString("---\n")
	fmt.Fprintf(&b, "ts: %s\n", ts)
	fmt.Fprintf(&b, "title: %s\n", strings.TrimSpace(ep.title))
	fmt.Fprintf(&b, "touched: %s\n", touched)
	b.WriteString("---\n")
	b.WriteString(strings.TrimSpace(ep.body))
	b.WriteString("\n")
	return b.String()
}

// fallbackEpisodeTitle labels a digest whose model reply carried no
// title: the opening line of the chat, the same label the archive
// browser uses, or the generation stamp when nothing was said.
func fallbackEpisodeTitle(msgs []store.ChatMessage, ts string) string {
	for _, m := range msgs {
		if m.Kind == "tool_use" || m.Kind == "tool_result" || m.Kind == "rotation_prompt" || m.Kind == store.KindWakeUpdate {
			continue
		}
		line, _, _ := strings.Cut(strings.TrimSpace(m.Content), "\n")
		if line == "" {
			continue
		}
		if len(line) > 80 {
			line = truncateForSummary(line, 80) + "…"
		}
		return line
	}
	return "Chat archived " + ts
}

// renderEpisodeTranscript formats the archived chat as the user
// message Haiku digests.
//
// One block per message, labelled by who spoke (USER / AGENT / TOOL)
// and, for the user side, by how it arrived (direct chat, inbox
// delivery, CEO queue). Tool traffic is kept — it is most of what the
// agent actually did — but each tool block is cut to
// episodeToolExcerptChars so a 200 KB file_view result cannot crowd
// out the conversation around it.
//
// The rotation turn is dropped whole: the prompt, every agent_memory_*
// call it provoked, and each of their results. All of it is the same
// boilerplate in every generation and says nothing about this one, and
// keeping it is worse than keeping the prompt alone — the shortener
// below gives the tail 70% of the budget, so in a long chat the
// reconcile bookkeeping is precisely what survives, and the model is
// asked to digest a chat whose visible ending is an agent editing its
// own memory. Memory is rewritten only at rotation, so every
// agent_memory_* call in a transcript is reconcile bookkeeping and the
// rule needs no window. Results are matched to their call by
// ToolUseID so a non-memory result is never collateral damage.
//
// Over episodeInputCharCap, whole messages are elided from the middle
// — the opening keeps what was asked, the end keeps what was
// concluded, and the cut is marked where it happens so the model
// digests a shortened chat rather than inventing the join.
func renderEpisodeTranscript(msgs []store.ChatMessage) string {
	droppedResults := map[string]bool{}
	for _, m := range msgs {
		if m.Kind == "tool_use" && m.ToolUseID != "" && agent.IsAgentMemoryTool(m.ToolName) {
			droppedResults[m.ToolUseID] = true
		}
	}
	blocks := make([]string, 0, len(msgs))
	for _, m := range msgs {
		if m.Kind == "tool_result" && m.ToolUseID != "" && droppedResults[m.ToolUseID] {
			continue
		}
		if b := renderEpisodeBlock(m); b != "" {
			blocks = append(blocks, b)
		}
	}
	total := 0
	for _, b := range blocks {
		total += len(b) + 1
	}
	if total <= episodeInputCharCap {
		return strings.Join(blocks, "\n")
	}
	// Head gets ~30% of the budget, tail the rest. Both walk whole
	// blocks so no message is ever cut mid-sentence.
	headBudget := episodeInputCharCap * 3 / 10
	tailBudget := episodeInputCharCap - headBudget
	head := 0
	spent := 0
	for head < len(blocks) && spent+len(blocks[head])+1 <= headBudget {
		spent += len(blocks[head]) + 1
		head++
	}
	tail := len(blocks)
	spent = 0
	for tail > head && spent+len(blocks[tail-1])+1 <= tailBudget {
		spent += len(blocks[tail-1]) + 1
		tail--
	}
	elided := tail - head
	if elided <= 0 {
		return strings.Join(blocks, "\n")
	}
	out := make([]string, 0, head+1+len(blocks)-tail)
	out = append(out, blocks[:head]...)
	out = append(out, fmt.Sprintf("[... %d messages elided ...]", elided))
	out = append(out, blocks[tail:]...)
	return strings.Join(out, "\n")
}

func renderEpisodeBlock(m store.ChatMessage) string {
	switch m.Kind {
	case "rotation_prompt", store.KindWakeUpdate:
		// Runtime boilerplate: the same shape in every generation,
		// saying nothing about what this chat was for.
		return ""
	case "tool_use":
		if agent.IsAgentMemoryTool(m.ToolName) {
			return ""
		}
		return fmt.Sprintf("TOOL CALL %s: %s\n", m.ToolName, truncateForSummary(strings.TrimSpace(m.ToolInput), episodeToolExcerptChars))
	case "tool_result":
		label := "TOOL RESULT"
		if m.IsError {
			label = "TOOL ERROR"
		}
		return fmt.Sprintf("%s: %s\n", label, truncateForSummary(strings.TrimSpace(m.Content), episodeToolExcerptChars))
	}
	text := strings.TrimSpace(m.Content)
	if text == "" {
		return ""
	}
	who := "AGENT"
	if m.Role == store.RoleReceived {
		who = "USER"
		if m.Kind != "" && m.Kind != "direct_chat" {
			who = "USER (" + m.Kind + ")"
		}
	}
	return fmt.Sprintf("%s: %s\n", who, text)
}

// truncateForSummary cuts s to at most n bytes without splitting a
// UTF-8 rune, then backs up to the last line or word break in the tail
// of the excerpt so the model gets a whole word rather than a stump.
func truncateForSummary(s string, n int) string {
	if n <= 0 {
		return ""
	}
	if len(s) <= n {
		return s
	}
	cut := n
	for cut > 0 && !utf8.RuneStart(s[cut]) {
		cut--
	}
	excerpt := s[:cut]
	if idx := strings.LastIndexAny(excerpt, "\n "); idx > cut*4/5 {
		excerpt = excerpt[:idx]
	}
	return strings.TrimRight(excerpt, " \n")
}

const episodePromptSystem = `You are writing the episode record for one archived chat of an AI agent on a Kivali team. An episode is the immutable digest that future readers — the agent itself months from now, and the people who run it — will grep to find this chat again. Specificity is the whole job: a title that could describe a hundred chats is a failed title.

Output EXACTLY this shape and nothing else:

title: <one line, at most 80 characters, specific enough to tell this chat apart from every similar one — name the system, the decision, the file, or the person; never "debugging session", "status update", or "discussion">
touched: <comma-separated names of the files, systems, agents, or people this chat centred on; "-" if none>
---
Asked: <what the agent was asked to do, in one or two sentences>
Did: <what it actually did — the actions, in order, briefly>
Concluded: <what was decided, found, or delivered; keep numbers, names, and paths verbatim>
Left open: <what was unfinished, deferred, or blocked; "nothing" if none>

Rules:
  - Past tense, third person ("the agent"), plain prose. No bullets inside a field, no headings, no preamble, no closing remarks.
  - Copy identifiers exactly: file paths, hostnames, ticket numbers, error strings, agent names. They are what a later search will hit.
  - Say what was observed separately from what the agent concluded from it.
  - A long chat is shortened on purpose and marked "[... N messages elided ...]". Digest what you were given; never mention that anything was elided or missing.`
