// Code generated by tygo. DO NOT EDIT.
// Source: internal/web/apitypes. Regenerate with `make api-types`.

//////////
// source: agent_work.go

/**
 * Background is GET /api/v1/agents/{slug}/background: the agent's plan
 * for the work it is fanning out, if it wrote one, and every background
 * session it has dispatched since its chat began. Sessions are always
 * present (possibly empty); a plan without sessions and sessions
 * without a plan are both normal.
 */
export interface Background {
  plan?: BackgroundPlan;
  /**
   * Sessions are in dispatch order, oldest first, at every depth: a
   * worker a sub-lead dispatched follows it and names it in CallerID.
   * Nothing is capped; the UI folds long lists.
   */
  sessions: BackgroundSession[];
}
/**
 * PlanStepState is one plan step's state.
 */
/**
 * PlanStepStateDone is a ticked step.
 */
export const PlanStepStateDone = "done";
/**
 * PlanStepStateRunning is an unticked step with a session queued or
 * running under it.
 */
export const PlanStepStateRunning = "running";
/**
 * PlanStepStateIdle is an unticked step with nothing live under it and
 * no failure as its latest outcome.
 */
export const PlanStepStateIdle = "idle";
/**
 * PlanStepStateNeedsHelp is an unticked step whose latest session failed,
 * with nothing live under it. A cancelled session does not count:
 * someone called it off.
 */
export const PlanStepStateNeedsHelp = "needs_help";
export type PlanStepState = typeof PlanStepStateDone | typeof PlanStepStateRunning | typeof PlanStepStateIdle | typeof PlanStepStateNeedsHelp;
/**
 * BackgroundPlan is the agent's plan file, read as a list of steps.
 */
export interface BackgroundPlan {
  /**
   * Title is the plan's first heading, or its first line.
   */
  title: string;
  steps: PlanStep[];
  /**
   * Done and Total count steps.
   */
  done: number /* int */;
  total: number /* int */;
  /**
   * Running and Finished count sessions, at every depth, as the
   * header's "2 running · 9 finished" reads.
   */
  running: number /* int */;
  finished: number /* int */;
  /**
   * NeedsHelp counts steps in state needs_help.
   */
  needs_help: number /* int */;
}
/**
 * PlanStep is one checkbox line of the plan. N is its 1-based position,
 * which is the number a session's step refers to.
 */
export interface PlanStep {
  n: number /* int */;
  title: string;
  state: PlanStepState;
}
/**
 * SessionKind is what ran a background session. Only subagent exists
 * today; agent is reserved for work handed to another durable agent.
 */
export const SessionKindSubagent = "subagent";
export const SessionKindAgent = "agent";
export type SessionKind = typeof SessionKindSubagent | typeof SessionKindAgent;
/**
 * SessionState is a background session's state.
 */
export const SessionStateQueued = "queued";
export const SessionStateRunning = "running";
export const SessionStateDone = "done";
export const SessionStateErrored = "errored";
export const SessionStateCancelled = "cancelled";
export type SessionState = typeof SessionStateQueued | typeof SessionStateRunning | typeof SessionStateDone | typeof SessionStateErrored | typeof SessionStateCancelled;
/**
 * BackgroundSession is one dispatched background task.
 */
export interface BackgroundSession {
  id: string;
  kind: SessionKind;
  state: SessionState;
  /**
   * Title is the description the agent gave the task.
   */
  title: string;
  /**
   * Model is the friendly name ("Opus 5.5"); Effort the level.
   */
  model: string;
  effort: string;
  /**
   * ElapsedS is seconds since the session started (or was dispatched,
   * if it never started), frozen at its end once it has one.
   */
  elapsed_s: number /* int64 */;
  /**
   * Step is the plan step's N the session works on, when it can be
   * told (see buildBackground in internal/web). A worker inherits its
   * sub-lead's step. The UI indents a session under its step.
   */
  step?: number /* int */;
  /**
   * Error is the failure in words, on an errored session only.
   */
  error?: string;
  /**
   * Activity is what a live session is doing now ("running
   * file_view"); absent once it ends.
   */
  activity?: string;
  /**
   * CallerID is the session that dispatched this one; absent for one
   * the agent dispatched itself.
   */
  caller_id?: string;
  /**
   * Started is when the session was admitted, or dispatched if it has
   * not been.
   */
  started: string /* RFC 3339 */;
  ended?: string /* RFC 3339 */;
  /**
   * URL is the app page for the session's transcript.
   */
  url: string;
}
/**
 * AgentDocKind names one of the About tab's documents. habits is the
 * document stored as the agent's operating principles.
 */
export const AgentDocKindRole = "role";
export const AgentDocKindHabits = "habits";
export const AgentDocKindMemory = "memory";
export type AgentDocKind = typeof AgentDocKindRole | typeof AgentDocKindHabits | typeof AgentDocKindMemory;
/**
 * AgentDoc is GET and PUT /api/v1/agents/{slug}/docs/{kind}.
 */
export interface AgentDoc {
  kind: AgentDocKind;
  content: string;
  /**
   * UpdatedAt is null when the document has never been written.
   */
  updated_at: string | null;
  stats: AgentDocStats;
}
/**
 * AgentDocStats is the one-line description's numbers.
 */
export interface AgentDocStats {
  lines: number /* int */;
  chars: number /* int */;
  /**
   * Notes is how many entries the agent memory holds; memory only.
   */
  notes?: number /* int */;
}
/**
 * AgentDocPut is the body of PUT /api/v1/agents/{slug}/docs/{kind}.
 */
export interface AgentDocPut {
  content: string;
}

//////////
// source: apitypes.go
/*
Package apitypes is the wire contract between the Go server and the
Kivali web app: every JSON body under /api/v1/ and the payload of the
/org/stream `snapshot` event.

tygo reads this package and writes web/src/api/types.gen.ts (`make
api-types`), so the TypeScript the screens compile against is derived
from these declarations and nothing else. Rules:

  - Pure data. No imports beyond the standard library, no methods
    that carry business logic, no types from internal/store or
    internal/provider; the handlers map into these.
  - Every field has an explicit snake_case json tag.
  - No nil slices in a response. An empty list is `[]`, never null or
    absent, so the client never needs an existence check. NoNilSlices
    enforces it on the golden fixtures and in handler tests.
  - A field that is legitimately absent is a pointer with omitempty,
    which tygo renders as an optional property.
*/

/**
 * ErrorBody is every error response under /api/: what happened, then
 * who can fix it.
 */
export interface ErrorBody {
  error: string;
  who: string;
}
/**
 * Me is GET /api/v1/me: who is signed in and which org they are in.
 */
export interface Me {
  user: MeUser;
  org: MeOrg;
  version: string;
  dev_mode: boolean;
}
/**
 * MeUser is the signed-in person. The session carries only an email,
 * so Name and Initials are derived from its local part.
 */
export interface MeUser {
  email: string;
  name: string;
  initials: string;
}
/**
 * MeOrg is the current org's identity. Name is empty until the owner
 * sets one; HasLogo says whether /branding/* serves an uploaded mark.
 */
export interface MeOrg {
  name: string;
  has_logo: boolean;
  /**
   * OwnerName is what the person this team works for asked agents to
   * call them; absent when they chose nothing, and always on the
   * public GET /api/v1/login.
   */
  owner_name?: string;
}
/**
 * AgentState is one agent's run state as the new UI shows it, derived
 * from the liveness flags that travel beside it.
 */
export const AgentStateRunning = "running";
export const AgentStateWaiting = "waiting";
export const AgentStateIdle = "idle";
export const AgentStateNeedsHelp = "needs_help";
export const AgentStateQuarantined = "quarantined";
export const AgentStateDisconnected = "disconnected";
export type AgentState = typeof AgentStateRunning | typeof AgentStateWaiting | typeof AgentStateIdle | typeof AgentStateNeedsHelp | typeof AgentStateQuarantined | typeof AgentStateDisconnected;
/**
 * OrgSnapshot is the payload of every /org/stream `snapshot` event and
 * of GET /api/v1/snapshot. The server publishes a new one only when the
 * marshalled bytes change, so every field must marshal stably: agents
 * in tree order, lists sorted.
 */
export interface OrgSnapshot {
  /**
   * Agents is every active agent except the CEO, in tree order: a
   * depth-first walk of the reporting lines, siblings by slug.
   */
  agents: SnapshotAgent[];
  inbox: SnapshotInbox;
  release: SnapshotRelease;
  /**
   * MessagesTotal is the count of messages on disk; a change is the
   * client's cue to refetch history.
   */
  messages_total: number /* int */;
  /**
   * AssignmentsVersion changes on every tracker write in this process. It
   * is a counter, not a timestamp: compare for inequality only.
   */
  assignments_version: number /* int64 */;
  /**
   * Goals are the open top-level assignments that have parts or
   * Done-when conditions, ascending by id.
   */
  goals: Goal[];
  readouts: Readouts;
}
/**
 * SnapshotAgent is one agent's liveness: State, derived on the server
 * from flags that stay there (web.lifecycle), and the count of
 * background jobs it waits on.
 */
export interface SnapshotAgent {
  slug: string;
  /**
   * Name is the label the sidebar tree shows: the role title, or the
   * slug when the agent has none.
   */
  name: string;
  role_title: string;
  /**
   * Icon is the role icon its avatar shows; empty for initials only.
   */
  icon: string;
  /**
   * ReportsTo is the manager's slug; "ceo" for the CEO's direct
   * reports.
   */
  reports_to: string;
  /**
   * Depth is the tree depth: 1 for the CEO's direct reports.
   */
  depth: number /* int */;
  state: AgentState;
  /**
   * ContextPct is how full the current chat's context window is,
   * 0..100. 0 when the agent has no chat history.
   */
  context_pct: number /* int */;
  /**
   * WaitingTasks is how many background subagent jobs this agent
   * still owns; the sidebar says so beside a waiting agent.
   */
  waiting_tasks?: number /* int */;
}
/**
 * SnapshotInbox is the CEO-facing aggregate: what needs a decision and
 * what is queued for release.
 */
export interface SnapshotInbox {
  unactioned: number /* int */;
  /**
   * PendingPaths is every queued message path, de-duplicated and
   * sorted.
   */
  pending_paths: string[];
  /**
   * CEOPaths is the request path of every unactioned item in the
   * CEO's inbox, sorted.
   */
  ceo_paths: string[];
  /**
   * AutoRelease is the slider's detent: now, 30s, 2m, 5m, 20m or off.
   */
  auto_release: AutoRelease;
}
/**
 * SnapshotRelease is the release engine's state.
 */
export interface SnapshotRelease {
  running: boolean;
  active_agents: number /* int */;
  pending_docs: number /* int */;
}
/**
 * Goal is an open top-level assignment with its rolled-up progress.
 */
export interface Goal {
  id: number /* int */;
  title: string;
  /**
   * Owner is the goal's assignee.
   */
  owner: string;
  /**
   * Done and Total count Done-when conditions when the goal declares
   * any; otherwise its parts, leaving dropped parts out of both.
   */
  done: number /* int */;
  total: number /* int */;
  /**
   * Blocked lists every dependency wait inside the goal: an open
   * assignment in it (the goal or a part at any depth) that waits on
   * another open assignment. Waiting on its own parts is progress,
   * not blockage, so those edges are left out.
   */
  blocked: GoalBlocker[];
  /**
   * Workers are the distinct assignees of the goal's open parts at
   * any depth, sorted.
   */
  workers: string[];
}
/**
 * GoalBlocker is one dependency wait: assignment ID waits on
 * assignment On, whose title is OnTitle and whose assignee is
 * OnAssignee (absent when On has no assignee).
 */
export interface GoalBlocker {
  id: number /* int */;
  on: number /* int */;
  on_title: string;
  on_assignee?: PersonRef;
}
/**
 * Readouts are Home's In flight numbers.
 */
export interface Readouts {
  /**
   * Working is how many agents are running a turn or waiting on
   * their own background work.
   */
  working: number /* int */;
  /**
   * Blocked is how many open assignments, not on hold, wait on
   * another open assignment (the same edges Goal.Blocked lists).
   */
  blocked: number /* int */;
  /**
   * ClosedWeek is how many assignments closed in the last seven days.
   */
  closed_week: number /* int */;
  /**
   * SpendToday is US dollars since 00:00 UTC; Spend7d over the last
   * seven days. Both priced from token counts at list rates; usage on
   * a model with no price is left out.
   */
  spend_today: number /* float64 */;
  spend_7d: number /* float64 */;
}
/**
 * AgentSummary is one agent in a list: the snapshot's identity fields
 * plus what it runs on.
 */
export interface AgentSummary {
  slug: string;
  name: string;
  role_title: string;
  icon: string;
  reports_to: string;
  depth: number /* int */;
  model: string;
  /**
   * ModelLabel is Model in words, from the provider ("Opus 5.5"); the
   * id itself when the provider does not know it.
   */
  model_label: string;
  effort: string;
  context_pct: number /* int */;
  state: AgentState;
  created: string /* RFC 3339 */;
  /**
   * ArchivedAt is set only on archived agents.
   */
  archived_at?: string /* RFC 3339 */;
}
/**
 * AgentsResponse is GET /api/v1/agents. Agents is in tree order;
 * Archived is by slug, with depth 0 and state idle.
 */
export interface AgentsResponse {
  agents: AgentSummary[];
  archived: AgentSummary[];
}
/**
 * ModelOption is one entry of the model picker, as the org's provider
 * describes it. Legacy marks the agent's current pin when the picker no
 * longer offers it; a legacy pin the provider does not know carries
 * only its id (as id and label) and no efforts.
 */
export interface ModelOption {
  id: string;
  label: string;
  /**
   * Legacy marks the agent's own pin when the picker no longer
   * offers it.
   */
  legacy: boolean;
  /**
   * Current is true for a model a person may newly pick.
   */
  current: boolean;
  /**
   * ContextWindow is the tokens the model holds.
   */
  context_window: number /* int */;
  /**
   * Efforts are the reasoning levels the model offers, low to high,
   * one of them the default. Empty: the model has no reasoning
   * control, and the effort chip hides.
   */
  efforts: EffortOption[];
  /**
   * Provider names the provider that runs the model ("claude").
   */
  provider: string;
}
/**
 * EffortOption is one reasoning level a model offers. An agent's or a
 * subagent's effort field holds the ID.
 */
export interface EffortOption {
  id: string;
  label: string;
  default: boolean;
}
/**
 * ContextFill is the chat header's context gauge.
 */
export interface ContextFill {
  pct: number /* int */;
  tokens: number /* int */;
  limit: number /* int */;
}
/**
 * AgentCounts are the numbers on the agent's tabs.
 */
export interface AgentCounts {
  /**
   * Background is how many background tasks the agent has running.
   */
  background: number /* int */;
  past_chats: number /* int */;
}
/**
 * AgentDetail is GET /api/v1/agents/{slug}.
 */
export interface AgentDetail extends AgentSummary {
  /**
   * RoleLine is the first line of the agent's role document, or its
   * role title when the document is empty.
   */
  role_line: string;
  models: ModelOption[];
  context: ContextFill;
  counts: AgentCounts;
  archived: boolean;
}
/**
 * AutoRelease is a detent on the auto-release slider.
 */
export const AutoReleaseNow = "now";
export const AutoRelease30s = "30s";
export const AutoRelease2m = "2m";
export const AutoRelease5m = "5m";
export const AutoRelease20m = "20m";
export const AutoReleaseOff = "off";
export type AutoRelease = typeof AutoReleaseNow | typeof AutoRelease30s | typeof AutoRelease2m | typeof AutoRelease5m | typeof AutoRelease20m | typeof AutoReleaseOff;
/**
 * AutoReleaseRequest is the body of POST /api/v1/auto-release.
 */
export interface AutoReleaseRequest {
  value: AutoRelease;
}
/**
 * AutoReleaseResponse echoes the setting now in force.
 */
export interface AutoReleaseResponse {
  value: AutoRelease;
}

//////////
// source: chat.go

/**
 * TranscriptKind discriminates TranscriptRow.
 */
/**
 * TranscriptKindMessage is a chat bubble: you writing to the agent, or
 * the agent writing back.
 */
export const TranscriptKindMessage = "message";
/**
 * TranscriptKindDelivery is a message another agent (or the tracker)
 * sent, delivered into this chat. It renders as a card from its
 * sender.
 */
export const TranscriptKindDelivery = "delivery";
/**
 * TranscriptKindCEOQueue is something the agent sent you: an approval
 * request or a notification, answered from Home.
 */
export const TranscriptKindCEOQueue = "ceo_queue";
/**
 * TranscriptKindToolUse is one tool call with its result folded in.
 */
export const TranscriptKindToolUse = "tool_use";
/**
 * TranscriptKindDocPublished is a message the agent published to
 * another agent.
 */
export const TranscriptKindDocPublished = "doc_published";
/**
 * TranscriptKindFileShared is files the agent shared into the chat.
 */
export const TranscriptKindFileShared = "file_shared";
/**
 * TranscriptKindSubagents is one batch of background tasks.
 */
export const TranscriptKindSubagents = "subagents";
/**
 * TranscriptKindTaskResult is a background task's report, delivered
 * to the agent when the task ended. It renders where it landed, as
 * the task it reports on.
 */
export const TranscriptKindTaskResult = "task_result";
/**
 * TranscriptKindMarker is a turn boundary the runtime recorded.
 */
export const TranscriptKindMarker = "marker";
/**
 * TranscriptKindWakeUpdate is the runtime's note at a wake. The model
 * reads it; the UI hides it by default.
 */
export const TranscriptKindWakeUpdate = "wake_update";
/**
 * TranscriptKindRotationPrompt is the request to fold the chat into
 * memory before a new chat starts.
 */
export const TranscriptKindRotationPrompt = "rotation_prompt";
export type TranscriptKind = typeof TranscriptKindMessage | typeof TranscriptKindDelivery | typeof TranscriptKindCEOQueue | typeof TranscriptKindToolUse | typeof TranscriptKindDocPublished | typeof TranscriptKindFileShared | typeof TranscriptKindSubagents | typeof TranscriptKindTaskResult | typeof TranscriptKindMarker | typeof TranscriptKindWakeUpdate | typeof TranscriptKindRotationPrompt;
/**
 * MessageRole is which side of the conversation a message is on, seen
 * from the person using the app: sent is yours, received is an
 * agent's.
 */
export const MessageRoleSent = "sent";
export const MessageRoleReceived = "received";
export type MessageRole = typeof MessageRoleSent | typeof MessageRoleReceived;
/**
 * PartyKind says whether a ChatParty is a person or an agent.
 */
export const PartyKindPerson = "person";
export const PartyKindAgent = "agent";
export type PartyKind = typeof PartyKindPerson | typeof PartyKindAgent;
/**
 * ChatParty is who wrote a row. You are {person, "ceo", "You"}; an
 * agent is named as the rest of the app names it; a background task
 * is an agent whose slug is its task id.
 */
export interface ChatParty {
  kind: PartyKind;
  slug: string;
  name: string;
}
/**
 * ToolStatus is a tool call's state.
 */
export const ToolStatusRunning = "running";
export const ToolStatusDone = "done";
export const ToolStatusError = "error";
export type ToolStatus = typeof ToolStatusRunning | typeof ToolStatusDone | typeof ToolStatusError;
/**
 * SubagentTaskState is a background task's state.
 */
export const SubagentTaskStateRunning = "running";
export const SubagentTaskStateDone = "done";
export const SubagentTaskStateErrored = "errored";
export type SubagentTaskState = typeof SubagentTaskStateRunning | typeof SubagentTaskStateDone | typeof SubagentTaskStateErrored;
/**
 * MarkerKind is the boundary a marker row records. The four stored
 * kinds keep their on-disk spelling. rotation is never stored: the
 * stream sends it, as a chat_marker, when the turn that folds the chat
 * into memory starts, so an open page shows that a new chat was asked
 * for. Its ts is the rotation_prompt row's, which is what the chat
 * API's rows carry for the same moment.
 */
export const MarkerKindUserInterruption = "user-interruption";
export const MarkerKindRuntimeDisruption = "runtime-disruption";
export const MarkerKindTurnError = "turn-error";
export const MarkerKindPausedToDeliver = "paused-to-deliver";
export const MarkerKindRotation = "rotation";
export type MarkerKind = typeof MarkerKindUserInterruption | typeof MarkerKindRuntimeDisruption | typeof MarkerKindTurnError | typeof MarkerKindPausedToDeliver | typeof MarkerKindRotation;
/**
 * SubagentTask is one task in a subagents row.
 */
export interface SubagentTask {
  /**
   * Index is the task's position in the batch the agent dispatched.
   */
  index: number /* int */;
  /**
   * ID is empty until the dispatch receipt names it.
   */
  id: string;
  title: string;
  /**
   * Model is the friendly name ("Opus 5.5"); Effort the level.
   */
  model: string;
  effort: string;
  state: SubagentTaskState;
  error?: string;
  /**
   * OutputMD is the task's final answer, once it has one.
   */
  output_md?: string;
  /**
   * URL is the task transcript's JSON, present once ID is known.
   */
  url?: string;
}
/**
 * TranscriptRow is one row of a transcript. Kind says which fields are
 * set; a field not listed for a kind is absent.
 *   - message: role, from, body_md, attachments, pending, and for an
 *     agent's reply model and effort; quiet on a message that woke no
 *     one; is_error on a reply that is the error text of a failed model
 *     call; source_kind when the row is not a plain chat message
 *     (ceo_reply, …).
 *   - delivery: from, title, delivered_to, also_to, body_md,
 *     attachments, kind_badge, message_type, assignment_ref, replies_to,
 *     in_reply_to, raw_url. When the message file can no longer be
 *     read, body_md is the text the model saw, kind_badge is
 *     "delivery", and from, replies_to and message_type are absent.
 *   - ceo_queue: from, title, body_md, attachments, message_type, path,
 *     raw_url, resolved.
 *   - tool_use: tool_use_id, name, input, output, status, is_error,
 *     started_ts, ended_ts, input_truncated, output_truncated. A call
 *     without a result is running while the turn it belongs to may
 *     still be going; the stream's tool_result, matched on tool_use_id,
 *     finishes it. Input is the call's JSON as the model wrote it,
 *     output the result text. The current chat (GET .../chat) cuts
 *     each long string in the input, and a long output, ending the cut
 *     with "…" and setting input_truncated or output_truncated;
 *     GET .../tool-calls/{tool_use_id} answers the call in full. Past
 *     chats and task transcripts send both in full.
 *   - doc_published: tool_use_id, title, message_type, to, body_md,
 *     attachments, assignment_ref (when the message names one),
 *     raw_url (the stored markdown file, not a page). When the message
 *     file can no longer be read, title is the one the agent gave and
 *     body_md, message_type and assignment_ref are absent.
 *   - file_shared: from, body_md, attachments.
 *   - subagents: tool_use_id, tasks.
 *   - task_result: tasks, holding the one task that reported, as it
 *     ended. When the report names no task, tasks is empty and body_md
 *     is the report's text.
 *   - marker: marker_kind, text, body_md (the detail).
 *   - wake_update, rotation_prompt: body_md.
 */
export interface TranscriptRow {
  kind: TranscriptKind;
  ts: number /* int64 */;
  role?: MessageRole;
  from?: ChatParty;
  body_md?: string;
  attachments?: AttachmentRef[];
  model?: string;
  effort?: string;
  pending?: boolean;
  quiet?: boolean;
  is_error?: boolean;
  source_kind?: string;
  title?: string;
  delivered_to?: PersonRef;
  also_to?: PersonRef[];
  kind_badge?: string;
  message_type?: string;
  assignment_ref?: AssignmentRef;
  replies_to?: PersonRef;
  in_reply_to?: string;
  raw_url?: string;
  path?: string;
  resolved?: boolean;
  to?: PersonRef[];
  tool_use_id?: string;
  name?: string;
  input?: string;
  output?: string;
  status?: ToolStatus;
  started_ts?: number /* int64 */;
  ended_ts?: number /* int64 */;
  input_truncated?: boolean;
  output_truncated?: boolean;
  tasks?: SubagentTask[];
  marker_kind?: MarkerKind;
  text?: string;
}
/**
 * ChatMessageEvent is the payload of the `chat_message` stream event:
 * a message the agent received, now in the transcript. Kind is the
 * row's kind on disk: direct_chat is a message you sent, painted from
 * Content and Attachments; subagent_result is a background task's
 * report, painted from Row, the task_result row the chat API serves for
 * it. Content is the text the model read.
 */
export interface ChatMessageEvent {
  role: MessageRole;
  kind: string;
  content: string;
  ts: number /* int64 */;
  attachments: PendingAttachment[];
  row?: TranscriptRow;
}
/**
 * ChatFill is how full the agent's context window is. LongThreshold is
 * the token count past which a new chat is worth suggesting;
 * ResolvedModel is the model the limit was sized for.
 */
export interface ChatFill {
  pct: number /* int */;
  tokens: number /* int */;
  limit: number /* int */;
  bucket: string;
  long_threshold: number /* int */;
  resolved_model: string;
}
/**
 * ToolCallDetail is GET /api/v1/agents/{slug}/tool-calls/{tool_use_id}: one
 * call in the current chat with its input and output in full. Output
 * is empty while the call has no result.
 */
export interface ToolCallDetail {
  tool_use_id: string;
  input: string;
  output: string;
}
/**
 * Chat is GET /api/v1/agents/{slug}/chat.
 */
export interface Chat {
  rows: TranscriptRow[];
  /**
   * Pending is what you sent while the agent was mid-turn, not yet in
   * Rows. The stream narrates what happens to each.
   */
  pending: PendingMessage[];
  fill: ChatFill;
  models: ModelOption[];
  current_model: string;
  current_effort: string;
  /**
   * Running is true while a turn streams or background tasks run;
   * WaitingTasks counts the tasks.
   */
  running: boolean;
  waiting_tasks: number /* int */;
  archived: boolean;
  /**
   * Rotating is true while a new chat is on its way: the agent is
   * folding this chat into memory, after which it is archived. The
   * stream's rotation_done says when that has happened.
   */
  rotating: boolean;
  /**
   * Generation names this chat among the agent's chats: the archive
   * id of the chat before it, empty for the agent's first. It changes
   * when a new chat starts, and only then, so rows a page holds under
   * another generation belong to a chat that is now a past chat.
   */
  generation: string;
}
/**
 * ModelRequest is POST /api/v1/agents/{slug}/model. "default" clears
 * the agent's own pin.
 */
export interface ModelRequest {
  model: string;
}
/**
 * EffortRequest is POST /api/v1/agents/{slug}/effort. "default" clears
 * the agent's own level.
 */
export interface EffortRequest {
  effort: string;
}
/**
 * ChatSettings answers the model and effort posts: what the agent runs
 * on from its next turn.
 */
export interface ChatSettings {
  current_model: string;
  current_effort: string;
}
/**
 * StopResponse is POST /api/v1/agents/{slug}/stop. Stopped is false
 * when nothing was running.
 */
export interface StopResponse {
  stopped: boolean;
}
/**
 * NewChatResponse is POST /api/v1/agents/{slug}/new-chat. Started is
 * false when the chat was empty and there was nothing to fold.
 */
export interface NewChatResponse {
  started: boolean;
}
/**
 * SubagentMeta is a background task's header.
 */
export interface SubagentMeta {
  id: string;
  parent: string;
  state: SubagentTaskState;
  model: string;
  effort: string;
  description: string;
  /**
   * Started is 0 when nothing recorded it.
   */
  started: number /* int64 */;
  ended?: number /* int64 */;
  error?: string;
  /**
   * Step is the plan step the task works on. Nothing links a task to
   * a step yet, so it is always absent.
   */
  step?: string;
  /**
   * Activity is what a running task is doing now ("running Bash").
   */
  activity?: string;
}
/**
 * SubagentTranscript is GET /api/v1/agents/{slug}/subagents/{id}.
 */
export interface SubagentTranscript {
  meta: SubagentMeta;
  rows: TranscriptRow[];
}
/**
 * ChatRange is the first and last timestamp in a chat; both 0 for an
 * empty chat.
 */
export interface ChatRange {
  from: number /* int64 */;
  to: number /* int64 */;
}
/**
 * PastChat is one row of GET /api/v1/agents/{slug}/chats. TS is the
 * archive id, used in the detail URL. Title is the episode's title, or
 * the chat's opening line while the episode is being written. Tokens
 * is estimated from the transcript's length.
 */
export interface PastChat {
  ts: string;
  title: string;
  range: ChatRange;
  messages: number /* int */;
  tokens: number /* int */;
}
/**
 * PastChats is GET /api/v1/agents/{slug}/chats, newest first.
 */
export interface PastChats {
  chats: PastChat[];
}
/**
 * HabitsDiff is the agent's habits (operating principles) when the
 * new chat was asked for and after it had folded the chat in.
 */
export interface HabitsDiff {
  before: string;
  after: string;
}
/**
 * PastChatSummary is what a rotation left behind. DigestMD is empty
 * until the episode is written. MemoryAdded is the lines of memory
 * present after the rotation and not before it.
 */
export interface PastChatSummary extends PastChat {
  digest_md: string;
  memory_added: string[];
  habits_diff: HabitsDiff;
}
/**
 * PastChatDetail is GET /api/v1/agents/{slug}/chats/{ts}. PrevTS is the
 * chat before this one, NextTS the one after.
 */
export interface PastChatDetail {
  summary: PastChatSummary;
  rows: TranscriptRow[];
  prev_ts?: string;
  next_ts?: string;
}

//////////
// source: graph.go

/**
 * Graph is GET /api/v1/graph?q=&flagged=1&problems=1&owner=&offset=&limit=:
 * the knowledge graph as a compact list, artifacts grouped by owner.
 */
export interface Graph {
  readouts: GraphReadouts;
  /**
   * Owners are the owners with at least one matching node: you
   * first, then active agents by slug, then archived agents, then
   * owners no longer on the team, then Unowned (slug "").
   */
  owners: GraphOwner[];
  /**
   * Stale is always false: the graph maintainer's index is current
   * when it is served, and a load runs no pass that could fail. The
   * page still reads it.
   */
  stale: boolean;
}
/**
 * GraphReadouts count the whole graph, whatever the filters.
 */
export interface GraphReadouts {
  /**
   * Nodes is the number of artifacts (agents are the owners, not
   * nodes on the list).
   */
  nodes: number /* int */;
  /**
   * Flagged is how many artifacts rest on something withdrawn,
   * superseded, rejected, missing or itself flagged.
   */
  flagged: number /* int */;
  /**
   * Problems is how many artifacts carry an index finding: front
   * matter that was rejected, or a problem with one of its edges or
   * its length.
   */
  problems: number /* int */;
}
/**
 * GraphOwner is one owner's section.
 */
export interface GraphOwner {
  /**
   * Slug is "" for Unowned.
   */
  slug: string;
  name: string;
  /**
   * Count is how many of the owner's nodes match.
   */
  count: number /* int */;
  /**
   * Nodes is one page of them, by id.
   */
  nodes: NodeRow[];
  has_more: boolean;
}
/**
 * NodeRow is one node as a list row.
 */
export interface NodeRow {
  id: string;
  /**
   * Kind is requirement, decision, certificate or reference, or
   * "artifact" for authored material with no kind.
   */
  kind: string;
  type: string;
  /**
   * Title is the node's summary, or its path when it has none.
   */
  title: string;
  status: string;
  flagged: boolean;
  /**
   * Problem is the node's findings in words, when it has any.
   */
  problem?: string;
  /**
   * Updated is when its current version was recorded; absent when
   * it has none yet.
   */
  updated?: string /* RFC 3339 */;
  /**
   * Version is its current version number, 0 when it has none.
   */
  version: number /* int */;
}
/**
 * GraphNode is GET /api/v1/graph/nodes/{id}: every field the node
 * carries, and its text. The id may pin a version, owner/name@N (or
 * @<sha prefix>); the text is then that version's.
 */
export interface GraphNode {
  fields: GraphNodeFields;
  /**
   * Version is the version whose text BodyMD is: the pinned one, or
   * the current one. Absent for an agent or a node with no versions.
   */
  version?: GraphVersion;
  /**
   * BodyMD is the file as it was at Version, front matter and all.
   * Absent when there is no text to show; BodyNote then says why.
   */
  body_md?: string;
  body_note?: string;
}
/**
 * GraphNodeFields is a node as the index holds it.
 */
export interface GraphNodeFields {
  id: string;
  type: string;
  kind: string;
  owner: PersonRef;
  /**
   * Path is the file under the owner's public directory, or the
   * project file's name; empty for an agent.
   */
  path: string;
  status: string;
  /**
   * DeclaredStatus is what the owner wrote, when it differs from
   * the effective status (a superseded node).
   */
  declared_status: string;
  condition: string;
  check: string;
  source: string;
  summary: string;
  payload: string;
  manifested: boolean;
  /**
   * Rejected is why the front matter was refused, when it was.
   */
  rejected: string;
  about?: GraphRef;
  depends_on: GraphRef[];
  supersedes: GraphRef[];
  evidence: string[];
  flagged: boolean;
  flags: string[];
  problems: string[];
  versions: GraphVersion[];
  about_me: string[];
  dependents: string[];
  superseded_by: string[];
  /**
   * ReportsTo is an agent node's manager.
   */
  reports_to: string;
}
/**
 * GraphRef is an edge to another node, optionally pinned to one of
 * its versions. Resolved is false when the target or pin does not
 * exist.
 */
export interface GraphRef {
  id: string;
  pin: string;
  resolved: boolean;
}
/**
 * GraphVersion is one recorded version of an artifact. URL opens its
 * stored bytes; absent for your project files, which are opened from
 * the files page.
 */
export interface GraphVersion {
  n: number /* int */;
  at: string /* RFC 3339 */;
  sha: string;
  payload_sha: string;
  url?: string;
}

//////////
// source: home.go

/**
 * Home is GET /api/v1/home: everything the Home screen draws, top to
 * bottom. Goals and Readouts are the snapshot's own values (one
 * computation serves both), so In flight reads the same here as on
 * the stream.
 */
export interface Home {
  goals: Goal[];
  readouts: Readouts;
  needs: NeedItem[];
  queue: QueueItem[];
  /**
   * AutoRelease is the slider's detent, as in the snapshot.
   */
  auto_release: AutoRelease;
  /**
   * HistoryTotal is how many threads GET /api/v1/home/history pages
   * through.
   */
  history_total: number /* int */;
}
/**
 * PersonRef names an agent, or you (slug "ceo", name "You"). Name is
 * the agent's role title, or its slug when it has none or is no
 * longer on the team.
 */
export interface PersonRef {
  slug: string;
  name: string;
}
/**
 * AgentRef is an agent with the state the needs-help row shows.
 */
export interface AgentRef {
  slug: string;
  name: string;
  state: AgentState;
}
/**
 * AttachmentRef is a file on a message. URL downloads it; SizeBytes
 * is 0 when the stored file cannot be found.
 */
export interface AttachmentRef {
  name: string;
  size_bytes: number /* int64 */;
  url: string;
}
/**
 * AssignmentRef is the assignment a row is about. Title is empty when the
 * tracker no longer knows the id.
 */
export interface AssignmentRef {
  id: number /* int */;
  title: string;
}
/**
 * NeedKind is what a Needs-you row asks of you.
 */
/**
 * NeedKindApproval: approve or deny a request.
 */
export const NeedKindApproval = "approval";
/**
 * NeedKindNotification: acknowledge.
 */
export const NeedKindNotification = "notification";
/**
 * NeedKindAssignment: an assignment is yours; hand it back with a
 * resolution and outcome (POST /api/v1/assignments/{id}/close).
 */
export const NeedKindAssignment = "assignment";
/**
 * NeedKindNeedsHelp: an agent has stopped; open its chat.
 */
export const NeedKindNeedsHelp = "needs_help";
/**
 * NeedKindProposal: an approval that changes the org; review it on
 * the proposal page (ReviewPath).
 */
export const NeedKindProposal = "proposal";
export type NeedKind = typeof NeedKindApproval | typeof NeedKindNotification | typeof NeedKindAssignment | typeof NeedKindNeedsHelp | typeof NeedKindProposal;
/**
 * ProposalKind is which change a proposal makes.
 */
export const ProposalKindHire = "hire";
export const ProposalKindRoleUpdate = "role_update";
export const ProposalKindHandbookUpdate = "handbook_update";
export const ProposalKindOffboard = "offboard";
export const ProposalKindReorg = "reorg";
export type ProposalKind = typeof ProposalKindHire | typeof ProposalKindRoleUpdate | typeof ProposalKindHandbookUpdate | typeof ProposalKindOffboard | typeof ProposalKindReorg;
/**
 * NeedItem is one row of Needs you, newest first; needs-help rows
 * follow the requests, in tree order.
 */
export interface NeedItem {
  /**
   * ID is what the actions take: the request's message path for
   * approval, notification and proposal rows (the `path` field of
   * POST /api/v1/needs/*), "assignment:<id>" for an assignment, and
   * "agent:<slug>" for a needs-help row.
   */
  id: string;
  kind: NeedKind;
  proposal_kind?: ProposalKind;
  title: string;
  from: PersonRef;
  at: string /* RFC 3339 */;
  body_md: string;
  attachments: AttachmentRef[];
  assignment?: AssignmentRef;
  /**
   * ReviewPath is the proposal page for a proposal row.
   */
  review_path?: string;
  /**
   * Agent is the agent a needs-help row is about.
   */
  agent?: AgentRef;
  /**
   * RawURL opens the message file; absent on a needs-help row.
   */
  raw_url?: string;
}
/**
 * QueueKind is a queued message's kind badge.
 */
/**
 * QueueKindAssignment is the tracker waking an agent about an
 * assignment. It cannot be bounced; edit the assignment instead.
 */
export const QueueKindAssignment = "assignment";
/**
 * QueueKindNotice is a message one agent sent others.
 */
export const QueueKindNotice = "notice";
export type QueueKind = typeof QueueKindAssignment | typeof QueueKindNotice;
/**
 * QueueItem is one queued message: one row however many agents it
 * is addressed to. Newest first.
 */
export interface QueueItem {
  /**
   * Path is the message path the queue actions take.
   */
  path: string;
  kind: QueueKind;
  title: string;
  from: PersonRef;
  to: PersonRef[];
  body_md: string;
  attachments: AttachmentRef[];
  assignment?: AssignmentRef;
  queued_at: string /* RFC 3339 */;
  /**
   * ReleasesAt is when the message releases on its own. Absent when
   * it waits for you (Held).
   */
  releases_at?: string /* RFC 3339 */;
  /**
   * Held is true when the message has no release time: it was sent
   * while auto-release was off, or auto-release has been turned off
   * since.
   */
  held: boolean;
  raw_url: string;
}
/**
 * HistoryResponse is GET /api/v1/home/history?before=&limit=: threads
 * newest activity first. NextBefore is the cursor for the next page,
 * absent on the last one. The cursor is opaque.
 */
export interface HistoryResponse {
  threads: HistoryThread[];
  total: number /* int */;
  next_before?: string;
}
/**
 * HistoryThread is a message and every reply to it.
 */
export interface HistoryThread {
  /**
   * Path is the first message's path; stable across pages.
   */
  path: string;
  last_activity: string /* RFC 3339 */;
  request: HistoryMessage;
  replies: HistoryMessage[];
  /**
   * Decision is the newest decision among the replies: approved,
   * denied or acknowledged. Absent when nobody decided.
   */
  decision?: string;
}
/**
 * HistoryMessage is one message in a thread.
 */
export interface HistoryMessage {
  path: string;
  /**
   * Type is the message's type as stored (notice, assignment_event,
   * ceo_approval_request, ...); Label is its name in words.
   */
  type: string;
  label: string;
  title: string;
  from: PersonRef;
  to: PersonRef[];
  at: string /* RFC 3339 */;
  body_md: string;
  attachments: AttachmentRef[];
  assignment?: AssignmentRef;
  decision?: string;
  raw_url: string;
}
/**
 * QueueReleaseRequest is POST /api/v1/queue/release. Note, when set,
 * is appended to the message as your note before it goes out.
 */
export interface QueueReleaseRequest {
  path: string;
  note?: string;
}
/**
 * QueueReleaseAllRequest is POST /api/v1/queue/release-all. Without
 * Paths every queued message goes; with them, only those (paths no
 * longer queued are skipped), and an empty list releases nothing.
 * Notes are keyed by path.
 */
export interface QueueReleaseAllRequest {
  paths?: string[];
  notes?: { [key: string]: string};
}
/**
 * QueueReleaseResponse is how many messages went out.
 */
export interface QueueReleaseResponse {
  released: number /* int */;
}
/**
 * QueueBounceRequest is POST /api/v1/queue/bounce: the message is
 * cancelled and Comment goes back to its sender.
 */
export interface QueueBounceRequest {
  path: string;
  comment: string;
}
/**
 * NeedActionResponse answers POST /api/v1/needs/approve, deny and ack.
 * A proposal's answer says what changed, in words, and links where to
 * see it; any other request answers with an empty object.
 */
export interface NeedActionResponse {
  result?: string;
  link?: string;
}
/**
 * AssignmentCloseRequest is POST /api/v1/assignments/{id}/close: hand an
 * assignment back as done or dropped, with the outcome the asker
 * reads first.
 */
export interface AssignmentCloseRequest {
  resolution: AssignmentResolution;
  outcome: string;
}
/**
 * AssignmentResolution is how an assignment ended.
 */
export const AssignmentResolutionDone = "done";
export const AssignmentResolutionDropped = "dropped";
export type AssignmentResolution = typeof AssignmentResolutionDone | typeof AssignmentResolutionDropped;
/**
 * Empty is the body of a success with nothing to say.
 */
export interface Empty {
}

//////////
// source: org.go

/**
 * Usage is GET /api/v1/org/usage.
 * All spend is US dollars priced from each call's token counts at list
 * rates, the same pricing Home's spend readouts use, so the two pages
 * agree. A call on a model with no price adds nothing to spend; its
 * tokens are counted in UsageWindow.Unpriced instead.
 */
export interface Usage {
  tiles: UsageTiles;
  /**
   * Daily is spend per UTC day for the last 30 days, oldest first,
   * ending today. Always 30 entries: a day with no calls is 0.
   */
  daily: UsageDay[];
  /**
   * ByAgent is every agent with a call in the last 30 days, most
   * 30-day spend first (ties by slug). Calls made for no agent (inbox
   * and file summaries) are one row with an empty slug.
   */
  by_agent: UsageAgent[];
  windows: UsageWindows;
}
/**
 * UsageTiles are the three spend tiles.
 */
export interface UsageTiles {
  /**
   * Today is since 00:00 UTC, matching Home's spend today.
   */
  today: UsageTile;
  /**
   * D7 and D30 are the last 7 and 30 days before now.
   */
  d7: UsageTile;
  d30: UsageTile;
}
/**
 * UsageTile is one tile's figures.
 */
export interface UsageTile {
  spend: number /* float64 */;
  calls: number /* int */;
  /**
   * CacheHitPct is the share of input-side tokens served from the
   * prompt cache: cache reads over fresh input plus cache reads plus
   * cache writes, 0..100, rounded. 0 with no calls.
   */
  cache_hit_pct: number /* int */;
}
/**
 * UsageDay is one bar of "Spend per day".
 */
export interface UsageDay {
  /**
   * Date is the UTC day, YYYY-MM-DD.
   */
  date: string;
  spend: number /* float64 */;
}
/**
 * UsageAgent is one row of "Who spent it" and the By agent table.
 */
export interface UsageAgent {
  /**
   * Slug is empty for calls made for no agent.
   */
  slug: string;
  /**
   * Name is the agent's display name, the slug for an agent no
   * longer on file, "You" for the CEO, and "Kivali" for calls made
   * for no agent.
   */
  name: string;
  d7: number /* float64 */;
  d30: number /* float64 */;
}
/**
 * UsageWindows is the folded "Calls and tokens" table.
 */
export interface UsageWindows {
  h24: UsageWindow;
  d7: UsageWindow;
  d30: UsageWindow;
}
/**
 * UsageWindow is one column of the calls and tokens table.
 */
export interface UsageWindow {
  calls: number /* int */;
  /**
   * TokensIn is everything sent to the model: fresh input plus both
   * cache legs. TokensOut is what it wrote back.
   */
  tokens_in: number /* int */;
  tokens_out: number /* int */;
  cache_read: number /* int */;
  cache_create: number /* int */;
  spend: number /* float64 */;
  /**
   * Unpriced is the tokens (in plus out) on calls whose model has no
   * price, which Spend leaves out; UnpricedCalls is how many calls
   * those are.
   */
  unpriced: number /* int */;
  unpriced_calls: number /* int */;
}
/**
 * Org is GET /api/v1/org, and the answer to PUT /api/v1/org and the
 * logo upload and removal.
 */
export interface Org {
  /**
   * Name is empty until someone sets one.
   */
  name: string;
  has_logo: boolean;
  /**
   * LogoURL is the 512 px logo, present when HasLogo.
   */
  logo_url?: string;
  /**
   * Kind is what the team is for; empty when never set.
   */
  kind: TeamKind;
  /**
   * OwnerName is what the person this team works for asked agents to
   * call them ("Jane", "Mom"); empty when they chose nothing.
   */
  owner_name: string;
}
/**
 * OrgPut is the body of PUT /api/v1/org. An empty name clears it.
 * Kind, when present, changes the team's kind; it must be work or
 * personal. OwnerName, when present, changes what agents call the
 * person (trimmed, at most 40 characters); empty clears it.
 */
export interface OrgPut {
  name: string;
  kind?: TeamKind;
  owner_name?: string;
}
/**
 * Handbook is GET /api/v1/org/handbook and the answer to PUT.
 */
export interface Handbook {
  content: string;
  /**
   * Sections is Content split at `##` headings, as DocDiff's
   * splitSections does: text before the first heading is "Opening"
   * (left out when blank), and the heading line itself is not in
   * Lines.
   */
  sections: DocSection[];
  /**
   * Draft is true when no handbook has been saved: Content is the
   * starting draft Kivali ships with.
   */
  draft: boolean;
  /**
   * UpdatedAt is when it was last saved; absent for a draft.
   */
  updated_at?: string /* RFC 3339 */;
}
/**
 * DocSection is one `##` section of a markdown document.
 */
export interface DocSection {
  title: string;
  /**
   * Lines is the section's text line for line, blank lines included,
   * so joining them rebuilds it.
   */
  lines: string[];
  /**
   * LineCount is how many of Lines have text: what "N lines" on a
   * section counts.
   */
  line_count: number /* int */;
}
/**
 * HandbookPut is the body of PUT /api/v1/org/handbook.
 */
export interface HandbookPut {
  content: string;
}
/**
 * ProjectFiles is GET /api/v1/org/files and the answer to every files
 * mutation. Oldest upload first.
 */
export interface ProjectFiles {
  files: ProjectFile[];
}
/**
 * ProjectFile is one uploaded project file.
 */
export interface ProjectFile {
  sha: string;
  name: string;
  size_bytes: number /* int64 */;
  uploaded_at: string /* RFC 3339 */;
  /**
   * Extracted is true when agents can read the file as text (or, for
   * an image or PDF, as itself); false when nothing could be pulled
   * out of it.
   */
  extracted: boolean;
  /**
   * Kind is the knowledge-graph kind chosen at upload; empty reads as
   * reference.
   */
  kind: string;
  /**
   * Summary is a one-sentence description written shortly after
   * upload; empty until then or when the file has no text.
   */
  summary: string;
  /**
   * URL downloads the original upload.
   */
  url: string;
}
/**
 * FilesBulkDelete is the body of POST /api/v1/org/files/bulk-delete.
 */
export interface FilesBulkDelete {
  shas: string[];
}
/**
 * Skills is GET /api/v1/org/skills and the answer to every skills
 * mutation, by name.
 */
export interface Skills {
  skills: Skill[];
}
/**
 * Skill is one skill in the org's library.
 */
export interface Skill {
  name: string;
  version: string;
  enabled: boolean;
  /**
   * Builtin skills ship with Kivali: they can be switched off, never
   * replaced or deleted.
   */
  builtin: boolean;
  description: string;
  updated_at: string /* RFC 3339 */;
}
/**
 * SkillDowngrade is the 409 body of a skill upload whose version is
 * not newer than the installed one. Send the upload again with the
 * form field confirm_downgrade=true to replace it anyway.
 */
export interface SkillDowngrade {
  error: string;
  who: string;
  old_version: string;
  new_version: string;
}
/**
 * Network is GET /api/v1/org/network and the answer to every network
 * mutation: the hosts agents may reach, sorted.
 */
export interface Network {
  hosts: NetworkHost[];
}
/**
 * NetworkHost is one allowed host. A host covers itself and every
 * subdomain; a leading "*." means the same. Past that, "*" and "[a-z]"
 * match within one label ("*-aiplatform.googleapis.com").
 */
export interface NetworkHost {
  host: string;
}
/**
 * NetworkAdd is the body of POST /api/v1/org/network.
 */
export interface NetworkAdd {
  host: string;
}

//////////
// source: pending.go

/**
 * PendingAttachment is a file a pending message carries. The bytes are
 * already stored; restoring a deleted message never re-uploads.
 */
export interface PendingAttachment {
  sha: string;
  name: string;
}
/**
 * PendingMessage is the payload of the `pending_message` stream event,
 * one entry of GET …/chat's `pending`, and the body of a restore.
 */
export interface PendingMessage {
  /**
   * ID is stable for the message's whole pending life; every later
   * event and action names it.
   */
  id: string;
  text: string;
  /**
   * QueuedAt is when the server received the message. It is also the
   * ts the delivered row carries in the transcript.
   */
  queued_at: number /* int64 */;
  attachments: PendingAttachment[];
  /**
   * Deletable is false once the message has been handed to the
   * running turn: from then on only the agent can consume it.
   */
  deletable: boolean;
}
/**
 * PendingRef is the payload of `pending_offered` and `pending_deleted`.
 */
export interface PendingRef {
  id: string;
}
/**
 * PendingDelivered is the payload of `pending_delivered`: the message
 * is in the transcript now, keyed by TS (the same data-ts the
 * chat_message that may follow carries).
 */
export interface PendingDelivered {
  id: string;
  ts: number /* int64 */;
}
/**
 * ChatMarker is the payload of the `chat_marker` stream event: a
 * system row in the transcript. Kind is the row's kind on disk
 * ("user-interruption", "runtime-disruption", "turn-error",
 * "paused-to-deliver"), or "rotation" for a new chat that was asked
 * for: that one has no row of its own kind, TS is its rotation_prompt
 * row's and Content is empty.
 */
export interface ChatMarker {
  kind: string;
  content: string;
  ts: number /* int64 */;
}
/**
 * ChatMarkerPausedToDeliver is the kind of the marker a Send now
 * leaves: the turn output above it, the delivered messages below it.
 */
export const ChatMarkerPausedToDeliver = "paused-to-deliver";
/**
 * PendingRestoreResponse is POST …/pending/{id}/restore: the message as
 * `pending_message` describes it. When the agent was idle by the time
 * of the restore the message went straight into the transcript instead
 * of back into the queue; DeliveredTS is then set, and no
 * pending_message event is sent.
 */
export interface PendingRestoreResponse extends PendingMessage {
  delivered_ts?: number /* int64 */;
}
/**
 * MessagePostRequest is the JSON body of POST /agents/{slug}/messages
 * (and the /api/v1 alias) for a message without attachments; one with
 * attachments is sent as multipart/form-data (text, attachment).
 */
export interface MessagePostRequest {
  text: string;
}
/**
 * MessagePostResponse is POST /agents/{slug}/messages (and the
 * /api/v1 alias). PendingID is set when the agent was mid-turn and the
 * message is waiting rather than in the transcript; the client paints
 * a pending bubble keyed on it. Attachments is absent when the message
 * carried none.
 */
export interface MessagePostResponse {
  ts: number /* int64 */;
  attachments?: PendingAttachment[];
  pending_id?: string;
}

//////////
// source: proposals.go

/**
 * Proposal is GET /api/v1/proposals/{path...}: one proposal to change
 * the org (a hire, a role update, a handbook update, an offboard
 * or a reorg), everything its review page draws. Path is the request
 * message's path, the `path` that POST /api/v1/needs/approve and deny
 * take.
 */
export interface Proposal {
  path: string;
  kind: ProposalKind;
  title: string;
  proposer: PersonRef;
  /**
   * ProposedAt is when the request was sent.
   */
  proposed_at: string /* RFC 3339 */;
  /**
   * ReasonMD is the request's body: why the proposer asks.
   */
  reason_md: string;
  attachments: AttachmentRef[];
  summary: ProposalSummary;
  /**
   * Docs are the documents the proposal writes, in order. Empty for
   * an offboard and a reorg, which change no document.
   */
  docs: ProposalDoc[];
  /**
   * Resolved is present once you have approved or denied it.
   */
  resolved?: ProposalResolution;
  /**
   * OffboardSentence is what happens to an offboarded agent's files,
   * said beside the Approve button. Present on an offboard only.
   */
  offboard_sentence?: string;
}
/**
 * ProposalSummary is the summary card: the agent it is about (a hire,
 * a role update, an offboard), the moves of a reorg, and a line per
 * fact worth saying.
 */
export interface ProposalSummary {
  agent?: ProposalAgent;
  /**
   * Moves is a reorg's reporting-line changes; empty for any other
   * kind.
   */
  moves: ProposalMove[];
  facts: ProposalFact[];
}
/**
 * ProposalAgent is the agent tile. For a hire it describes the agent
 * the approval creates: its role title as its name, and the model and
 * effort a new agent starts on.
 */
export interface ProposalAgent {
  slug: string;
  name: string;
  role_title: string;
  icon: string;
  reports_to: PersonRef;
  /**
   * Model is the model id; ModelLabel is its name in words
   * ("Opus 5.5").
   */
  model: string;
  model_label: string;
  effort: string;
}
/**
 * ProposalMove is one reporting-line change in a reorg: Slug moves
 * under To.
 */
export interface ProposalMove {
  slug: string;
  name: string;
  /**
   * From is whom the agent reports to now. Absent when that is
   * already To, as it is once an approved move has landed.
   */
  from?: PersonRef;
  to: PersonRef;
  /**
   * Failed says why an approved move could not be made.
   */
  failed?: string;
}
/**
 * ProposalFact is one "label · value" line on the summary card.
 */
export interface ProposalFact {
  label: string;
  value: string;
}
/**
 * ProposalDocKey says which document a block is, for its icon.
 */
export const ProposalDocKeyRole = "role";
export const ProposalDocKeyMemory = "memory";
export const ProposalDocKeyHandbook = "handbook";
export type ProposalDocKey = typeof ProposalDocKeyRole | typeof ProposalDocKeyMemory | typeof ProposalDocKeyHandbook;
/**
 * ProposalDoc is one document the proposal writes, whole: the client
 * splits it into sections at `##` headings and diffs them. Before is
 * the document as it stands now, absent for a new document (a hire's)
 * and once an approved change has replaced it, when After is what is
 * live. Both end in exactly one newline.
 */
export interface ProposalDoc {
  key: ProposalDocKey;
  title: string;
  /**
   * Meta is the block's mono line: "role.md · 84 lines".
   */
  meta: string;
  before?: string;
  after: string;
  /**
   * BeforeIsCurrent is true on a denied proposal: Before is the
   * document as it is now, which may have changed since the proposal
   * was made (no earlier version is kept), so the page should say its
   * diff is against the current file. False while the proposal waits,
   * when the current file is exactly what an approval would replace.
   */
  before_is_current?: boolean;
}
/**
 * ProposalResolution is how you answered: the same result sentence and
 * link POST /api/v1/needs/approve or deny returned.
 */
export interface ProposalResolution {
  approved: boolean;
  at: string /* RFC 3339 */;
  result: string;
  link?: string;
}

//////////
// source: setup.go

/**
 * Login is GET /api/v1/login, the one API route served without a
 * session: what the sign-in screen needs before anyone has signed in.
 * It carries nothing else, since anyone can read it.
 */
export interface Login {
  /**
   * Org is the org's name and whether it has a logo. Name is empty
   * until the owner sets one.
   */
  org: MeOrg;
  /**
   * AuthReady says whether Google sign-in is configured (both its
   * client id and secret). False is the "Sign-in isn't set up yet"
   * state.
   */
  auth_ready: boolean;
  /**
   * DevMode is true when the server runs without sign-in, attributing
   * every request to one developer account.
   */
  dev_mode: boolean;
}
/**
 * SetupStep is one of setup's four steps, or done.
 */
export const SetupStepWelcome = "welcome";
export const SetupStepOrg = "org";
export const SetupStepFiles = "files";
export const SetupStepCoS = "cos";
export const SetupStepDone = "done";
export type SetupStep = typeof SetupStepWelcome | typeof SetupStepOrg | typeof SetupStepFiles | typeof SetupStepCoS | typeof SetupStepDone;
/**
 * Setup is GET /api/v1/setup, and the body every setup write answers
 * with, so the client can replace its state wholesale.
 */
export interface Setup {
  /**
   * Needed is true until a Chief of Staff exists.
   */
  needed: boolean;
  /**
   * Step is where setup should resume: done once the Chief of Staff
   * exists; cos while a hire is running or has failed; otherwise
   * welcome when nothing is set, org when files are uploaded but the
   * org has no name, files when the org is named but has no files, and
   * cos when both are there.
   */
  step: SetupStep;
  org: MeOrg;
  /**
   * Kind is what the team is for; empty when it was never set, which
   * setup treats as work.
   */
  kind: TeamKind;
  files: SetupFile[];
  cos: SetupCoS;
  /**
   * Credential says whether a model is connected and how calls are
   * paid for; seeding needs a model.
   */
  credential: SetupCredential;
  /**
   * RestoreAvailable is true while the server holds nothing a backup
   * restore would overwrite.
   */
  restore_available: boolean;
}
/**
 * TeamKind is what a team is for: work runs a business, personal helps
 * one person with their life. Unset is a team created before kinds
 * existed, or one nobody chose a kind for; it behaves as work.
 */
export const TeamKindUnset = "";
export const TeamKindWork = "work";
export const TeamKindPersonal = "personal";
export type TeamKind = typeof TeamKindUnset | typeof TeamKindWork | typeof TeamKindPersonal;
/**
 * SetupFile is one uploaded project file, oldest first.
 */
export interface SetupFile {
  sha: string;
  name: string;
  size_bytes: number /* int64 */;
  /**
   * Extracted is true when the file has a text form the Chief of Staff
   * reads in full; false files are named to it but not read.
   */
  extracted: boolean;
}
/**
 * SetupCoS is the Chief of Staff step's starting point.
 */
export interface SetupCoS {
  exists: boolean;
  /**
   * DefaultRoleMD is the role document a new Chief of Staff gets.
   */
  default_role_md: string;
  /**
   * DefaultHandbookMD is the handbook seeding would use: the
   * stored one when there is one, else the built-in default.
   */
  default_handbook_md: string;
}
/**
 * SetupCredential says whether the model is connected and how calls
 * are paid for.
 */
export interface SetupCredential {
  /**
   * Ready is true when the server has a model driver; seeding needs
   * one.
   */
  ready: boolean;
  /**
   * Provider names the org's model provider ("claude").
   */
  provider: string;
  /**
   * Present is true when the provider reports it is signed in.
   */
  present: boolean;
  /**
   * Who is the signed-in identity when the provider reports one.
   */
  who: string;
  /**
   * Billing names what calls are billed to, in the provider's words
   * ("Claude Max", "Anthropic Console", "Amazon Bedrock", "Google
   * Vertex AI"); empty when not signed in or not reported.
   */
  billing: string;
  /**
   * Guidance is one plain sentence saying what is missing and who can
   * fix it. Empty when Ready.
   */
  guidance: string;
}
/**
 * SetupOrgRequest is the body of POST /api/v1/setup/org.
 */
export interface SetupOrgRequest {
  name: string;
}
/**
 * SeedCoSRequest is the body of POST /api/v1/setup/seed-cos. It
 * answers 202 with an empty body and the hire runs in the background;
 * GET /api/v1/setup/progress follows it.
 */
export interface SeedCoSRequest {
  /**
   * HandbookFromFiles asks the new Chief of Staff, in its first
   * message, to draft the handbook's company section from the
   * project files and propose it, or to ask the CEO what the files
   * leave out. The handbook written at seeding is then the
   * default (or HandbookMD), to be replaced by that proposal.
   */
  handbook_from_files: boolean;
  /**
   * RoleMD replaces the default role document. Send it only when the
   * CEO edited it.
   */
  role_md?: string;
  /**
   * HandbookMD replaces the handbook seeding writes. Send it
   * only when the CEO edited it.
   */
  handbook_md?: string;
}
/**
 * SetupProgressState is where the Chief of Staff hire stands.
 */
export const SetupProgressStateIdle = "idle";
export const SetupProgressStateRunning = "running";
export const SetupProgressStateDone = "done";
export const SetupProgressStateFailed = "failed";
export type SetupProgressState = typeof SetupProgressStateIdle | typeof SetupProgressStateRunning | typeof SetupProgressStateDone | typeof SetupProgressStateFailed;
/**
 * SetupStageState is one stage's state; it maps onto AgentState on the
 * hiring panel.
 */
export const SetupStageStateDone = "done";
export const SetupStageStateRunning = "running";
export const SetupStageStateQueued = "queued";
export const SetupStageStateFailed = "failed";
export type SetupStageState = typeof SetupStageStateDone | typeof SetupStageStateRunning | typeof SetupStageStateQueued | typeof SetupStageStateFailed;
/**
 * SetupStage is one line of the hiring panel. The labels name the
 * seed's real steps: "Reading your files", "Writing its first
 * briefing" (the one long model call), "Hiring", and, when the
 * handbook is to come from the files, "Asking it to draft the
 * handbook".
 */
export interface SetupStage {
  label: string;
  state: SetupStageState;
}
/**
 * SetupProgress is GET /api/v1/setup/progress. Idle has no stages;
 * done after a restart (the Chief of Staff exists but this process did
 * not hire it) has none either.
 */
export interface SetupProgress {
  state: SetupProgressState;
  stages: SetupStage[];
  /**
   * ElapsedS is whole seconds since the hire started, frozen when it
   * finishes.
   */
  elapsed_s: number /* int */;
  /**
   * Error and Who are set only on failed: what happened and who can
   * fix it.
   */
  error?: string;
  who?: string;
}

//////////
// source: work.go

/**
 * WorkItemState is where one assignment stands on the Work board and
 * on its detail page. Derived from the tracker every read, never
 * stored:
 *   - closed: closed, as done or dropped.
 *   - on_hold: open and on hold, by its own hold or an enclosing one.
 *   - blocked: open, not on hold, and waiting on another open
 *     assignment it names (a dependency outside its own parts).
 *   - moving: open, not on hold, waiting on nothing but its own open
 *     parts: the work is under way through them.
 *   - ready: open, not on hold, waiting on nothing; whoever holds it
 *     can act on it now.
 * A hold outranks a block, and waiting on one's own parts is progress,
 * not blockage, as in Goal.Blocked.
 */
export const WorkItemStateReady = "ready";
export const WorkItemStateMoving = "moving";
export const WorkItemStateBlocked = "blocked";
export const WorkItemStateOnHold = "on_hold";
export const WorkItemStateClosed = "closed";
export type WorkItemState = typeof WorkItemStateReady | typeof WorkItemStateMoving | typeof WorkItemStateBlocked | typeof WorkItemStateOnHold | typeof WorkItemStateClosed;
/**
 * WorkBoard is GET /api/v1/work: the board by goal.
 */
export interface WorkBoard {
  readouts: WorkReadouts;
  /**
   * Goals are the open goals, in the snapshot's order (ascending by
   * id), each with its three columns.
   */
  goals: WorkGoal[];
  /**
   * ClosedGoals are the goals (top-level assignments with parts or
   * Done-when conditions) closed within the last seven days, most
   * recently closed first.
   */
  closed_goals: ClosedGoal[];
}
/**
 * WorkReadouts are the numbers across the top of the board. Open,
 * ready, blocked and on hold count every open assignment, goals
 * included; blocked leaves out assignments on hold, as the Home
 * readout does. ClosedWeek counts every assignment closed in the last
 * seven days, as the snapshot's readout does: goals and top-level
 * assignments too, so it is at least the sum of the goals' LookBack
 * lengths and usually more.
 */
export interface WorkReadouts {
  open: number /* int */;
  ready: number /* int */;
  blocked: number /* int */;
  on_hold: number /* int */;
  closed_week: number /* int */;
}
/**
 * WorkGoal is one goal's block: the header, then three columns over
 * the goal's parts at any depth. The client groups each column's
 * items by owner.
 */
export interface WorkGoal {
  id: number /* int */;
  title: string;
  owner: PersonRef;
  /**
   * Done and Total are the snapshot goal's (Goal.Done, Goal.Total).
   */
  done: number /* int */;
  total: number /* int */;
  /**
   * State is the goal's own state (never closed here).
   */
  state: WorkItemState;
  /**
   * LookBack is the parts closed in the last seven days, most
   * recently closed first.
   */
  look_back: WorkItem[];
  /**
   * Current is the open parts that are moving, blocked or on hold,
   * ascending by id.
   */
  current: WorkItem[];
  /**
   * LookForward is the open parts that are ready, ascending by id.
   */
  look_forward: WorkItem[];
  /**
   * Unclaimed is the goal's own Done-when conditions that no part
   * names yet, in declared order. A part's own unclaimed conditions
   * show on its row (WorkItem.Acceptance), not here.
   */
  unclaimed: UnclaimedCondition[];
}
/**
 * WorkItem is one assignment on the board.
 */
export interface WorkItem {
  id: number /* int */;
  title: string;
  state: WorkItemState;
  /**
   * Owner is the assignee.
   */
  owner: PersonRef;
  /**
   * WaitingOn is what a blocked assignment waits on: the open
   * assignments it names, ascending, each with its state for the
   * reference chip. Empty otherwise.
   */
  waiting_on: AssignmentLink[];
  /**
   * HeldBy is who put the hold on, when the item is on hold.
   */
  held_by?: PersonRef;
  /**
   * Why says in words why a blocked or on-hold item cannot move:
   * "Waiting on #58 Fix the login redirect, assigned to Engineering lead",
   * "On hold by you", "On hold under #7 by you".
   */
  why?: string;
  /**
   * Acceptance counts the item's own Done-when conditions by state,
   * for the row's meter. Absent when it declares none.
   */
  acceptance?: ConditionProgress;
  /**
   * ClosedAt and Resolution are set on closed items.
   */
  closed_at?: string /* RFC 3339 */;
  resolution?: AssignmentResolution;
}
/**
 * UnclaimedCondition is a Done-when condition nothing opened names.
 */
export interface UnclaimedCondition {
  name: string;
}
/**
 * ClosedGoal is a goal closed in the last seven days.
 */
export interface ClosedGoal {
  id: number /* int */;
  title: string;
  owner: PersonRef;
  closed_at: string /* RFC 3339 */;
  resolution: AssignmentResolution;
}
/**
 * Assignment is GET /api/v1/assignments/{id}: one assignment with
 * everything its detail page shows.
 */
export interface Assignment {
  id: number /* int */;
  title: string;
  state: WorkItemState;
  /**
   * Why says in words why it cannot move (blocked or on hold).
   */
  why?: string;
  /**
   * HeldBy is who put the hold on, when it is on hold.
   */
  held_by?: PersonRef;
  /**
   * HeldHere is true when the hold is this assignment's own (Resume
   * applies to it) rather than an enclosing assignment's.
   */
  held_here: boolean;
  /**
   * Seq is the newest log entry's sequence number. Send it back on
   * POST …/update so an edit against a record that changed meanwhile
   * is refused rather than undoing the change.
   */
  seq: number /* int64 */;
  facts: AssignmentFacts;
  description_md: string;
  /**
   * Conditions are the Done-when conditions, in declared order.
   * Empty when it declares none.
   */
  conditions: AssignmentCondition[];
  progress: ConditionProgress;
  /**
   * Outcome is set once it is closed.
   */
  outcome?: AssignmentOutcome;
  /**
   * Log is every change, oldest first.
   */
  log: AssignmentLogEntry[];
  /**
   * Parts are its children, ascending by id.
   */
  parts: AssignmentLink[];
}
/**
 * AssignmentFacts are the eight facts at the top of the detail page.
 */
export interface AssignmentFacts {
  assignee: PersonRef;
  opened_by: PersonRef;
  opened: string /* RFC 3339 */;
  updated: string /* RFC 3339 */;
  part_of?: AssignmentLink;
  /**
   * WaitsOn is every assignment it names as a dependency, open or
   * closed, ascending.
   */
  waits_on: AssignmentLink[];
  /**
   * HoldsUp is the open assignments waiting on it: those naming it
   * as a dependency, and its parent while it is open.
   */
  holds_up: AssignmentLink[];
  /**
   * CountsToward is the parent's Done-when conditions this
   * assignment delivers.
   */
  counts_toward: CountsToward[];
}
/**
 * AssignmentLink names another assignment with its state and owner.
 */
export interface AssignmentLink {
  id: number /* int */;
  title: string;
  state: WorkItemState;
  owner: PersonRef;
}
/**
 * CountsToward is one Done-when condition of the parent (ID, Title)
 * that this assignment delivers when it closes as done.
 */
export interface CountsToward {
  id: number /* int */;
  title: string;
  condition: string;
}
/**
 * ConditionState is where one Done-when condition stands: satisfied
 * when a part naming it closed as done, claimed while an open part
 * names it, unclaimed when nothing opened names it.
 */
export const ConditionStateSatisfied = "satisfied";
export const ConditionStateClaimed = "claimed";
export const ConditionStateUnclaimed = "unclaimed";
export type ConditionState = typeof ConditionStateSatisfied | typeof ConditionStateClaimed | typeof ConditionStateUnclaimed;
/**
 * AssignmentCondition is one Done-when condition.
 */
export interface AssignmentCondition {
  name: string;
  state: ConditionState;
  /**
   * MetBy is the part whose done close met it: the earliest such
   * close when several parts name it.
   */
  met_by?: MetBy;
  /**
   * ClaimedBy is the open parts naming it, ascending.
   */
  claimed_by: AssignmentRef[];
}
/**
 * MetBy is the assignment that met a condition and when it closed.
 */
export interface MetBy {
  id: number /* int */;
  title: string;
  at: string /* RFC 3339 */;
}
/**
 * ConditionProgress counts the conditions by state; all zero when it
 * declares none.
 */
export interface ConditionProgress {
  satisfied: number /* int */;
  claimed: number /* int */;
  unclaimed: number /* int */;
}
/**
 * AssignmentOutcome is how it ended.
 */
export interface AssignmentOutcome {
  resolution: AssignmentResolution;
  text: string;
  at: string /* RFC 3339 */;
  /**
   * Unmet names the Done-when conditions still unmet when it closed
   * as done. Empty otherwise.
   */
  unmet: string[];
}
/**
 * AssignmentLogEntry is one change, in words. Text starts after the
 * actor ("reassigned it from Buyer to Tester"); Note is the reason the
 * actor gave.
 */
export interface AssignmentLogEntry {
  at: string /* RFC 3339 */;
  by: PersonRef;
  text: string;
  note?: string;
  /**
   * Ref is the assignment the change points at (a new parent, a
   * dependency added or removed).
   */
  ref?: AssignmentRef;
  /**
   * BeforeRef is the text as it was before an edit.
   */
  before_ref?: BeforeRef;
}
/**
 * BeforeRef points at a stored earlier text. Kind is "attachment":
 * Ref is its content hash and URL opens it.
 */
export interface BeforeRef {
  kind: string;
  ref: string;
  url: string;
}
/**
 * AssignmentReopenRequest reopens a closed assignment. Note says what is
 * wrong with the outcome; its assignee reads it first. Required.
 */
export interface AssignmentReopenRequest {
  note: string;
}
/**
 * AssignmentHoldRequest puts an assignment and everything under it on hold
 * (Held true) or resumes it (false). Note says why; everyone it wakes
 * reads it first. Required.
 */
export interface AssignmentHoldRequest {
  held: boolean;
  note: string;
}
/**
 * AssignmentUpdateRequest edits an open assignment. Absent fields are left
 * alone; a field equal to the record is no change. Note is required
 * when the change wakes someone else (a reassign, or an edit to
 * someone else's assignment). Seq, when sent, must be Assignment.Seq
 * as read: an edit against a record that has changed since is refused.
 */
export interface AssignmentUpdateRequest {
  title?: string;
  description_md?: string;
  assignee?: string;
  /**
   * Parent is the assignment it is part of; 0 makes it top-level.
   */
  parent?: number /* int */;
  /**
   * WaitsOn replaces the list of assignments it waits on.
   */
  waits_on?: number /* int */[];
  /**
   * Conditions replaces its Done-when conditions.
   */
  conditions?: string[];
  /**
   * CountsToward replaces the parent's conditions it delivers.
   */
  counts_toward?: string[];
  note?: string;
  seq?: number /* int64 */;
}
