// Package agentpod is the per-agent runtime that lives inside an
// agent Pod and the wire protocol that talks to the Kivali central
// process over a single Unix-domain socket on a shared hostPath.
//
// Architecture overview lives in docs/developers/architecture.md. In short:
//
//   - Core listens on /var/run/kivali/uds/core.sock; agent runtimes
//     always connect outbound.
//   - All API endpoints are HTTP-over-UDS, slug-namespaced under
//     /v1/agent/{slug}/... or /v1/... for content-addressed and
//     globally-shared resources.
//   - For events core wants to push (chat-turn wake-ups, cache
//     invalidations), the agent opens a long-lived SSE stream
//     outbound and reads server-pushed events on it. Same pattern
//     as the existing chat-hub SSE to the browser, sharable framing.
//
// This package's responsibilities split:
//
//   - protocol.go: wire types — events, request/response shapes —
//     used identically by client (agent runtime) and server (core).
//   - client.go: outbound UDS HTTP client used by the agent runtime
//     to dial core. Includes the events SSE consumer.
//   - manifest.go + provisioner.go + kube.go: per-agent Pod + PVC
//     lifecycle. Provision creates them on hire; Destroy removes
//     the Pod (PVC retained) on fire.
//   - shell.go: in-pod LocalShell that run_shell dispatches to.
package agentpod

import (
	"encoding/json"
	"net/http"

	"github.com/kivali-ai/kivali/internal/provider"
)

// EventType discriminates events on the agent's outbound SSE stream
// from core. Carried as the SSE "event:" line; the payload is a
// JSON object on the SSE "data:" line whose shape is one of the
// typed structs below.
type EventType string

const (
	// EventChatTurn — core wants the agent runtime to drive a chat
	// turn for this agent. Payload: ChatTurnEvent.
	EventChatTurn EventType = "chat-turn"

	// EventCancelTurn — core received a Stop click and wants the
	// agent runtime to abort the in-flight chat turn now (rather than
	// waiting for the model to complete its current chunk). Payload:
	// CancelTurnEvent. The runtime cancels the matching stream's
	// context; the post-cancel failed event carries
	// FailedReasonCancelled so core's handler skips the
	// runtime-disruption row (the user-interruption marker is the
	// right signal).
	EventCancelTurn EventType = "cancel-turn"

	// EventFoldMessage — core has a message for an agent whose turn is
	// ALREADY RUNNING, and wants it spliced into that turn rather than
	// ending the turn to deliver it.
	//
	// This is the cheap alternative to EventCancelTurn: the CLI folds
	// the message into the in-flight turn at
	// its next tool round, so nothing is aborted and no generated
	// output is discarded. The runtime answers with a TurnEventFolded
	// saying whether the running turn actually took it — including
	// when it refused outright, so core can fall back promptly.
	EventFoldMessage EventType = "fold-message"

	// EventCacheInvalidate — core hints that one or more cache keys
	// the agent might be holding are stale. Payload: CacheInvalidateEvent.
	// Optional: the per-resource version-tag mechanism is the primary
	// invalidation path; this is belt-and-suspenders for cases where
	// core wants immediate eviction without waiting for the next read.
	EventCacheInvalidate EventType = "cache-invalidate"

	// EventPing — heartbeat from core. Agents may answer with
	// POST /v1/agent/{slug}/ping-ack but the absence of an ack is
	// not an error condition; the SSE TCP keepalives carry liveness.
	EventPing EventType = "ping"

	// EventSessionReset — core archived a chat (rotation / New chat)
	// and cleared the stored CLI session id; the agent runtime must
	// tear down the warm `claude -p` subprocess for this slug so the
	// next turn starts a genuinely fresh session. Without this the
	// long-lived subprocess keeps the entire pre-rotation conversation
	// in memory and --resumes it, making rotation a no-op against the
	// model (the chat transcript rotates on disk, but Claude's context
	// window never resets). Payload: SessionResetEvent.
	EventSessionReset EventType = "session-reset"
)

// ChatTurnEvent is the payload core emits to ask the agent runtime
// to drive a chat turn. TurnID is generated by core; the runtime
// echoes it on every event it POSTs back via
// /v1/agent/{slug}/chat-turn/{turn-id}/event so core can correlate
// streamed output back to the originating turn.
//
// Source matches the today's chat hub Source string ("chat",
// "release", "rotation", etc.) so log lines and the chat-row
// "active-turn" marker stay legible across the boundary.
//
// Kind discriminates the turn type. Empty / "chat" means the parent
// agent's own model call — Request carries the prebuilt
// provider.CompleteRequest. "subagent" means a subagent run
// (provider.Client.RunSubagent) — Subagent carries the spec; Request is
// unset.
//
// Request carries the full provider.CompleteRequest as raw JSON for
// chat turns. We ship the request inline rather than asking the
// agent runtime to fetch chat history + system prompt + role +
// memory via separate UDS round-trips: the request is already built
// on the core side (via agent.Runtime.BuildChatContext +
// BuildRequest), and shipping it whole is one round trip vs. five+
// per turn. Payload size is comparable to a single user-message
// text post (~50 KB system prompt + recent history), well within
// UDS comfort.
type ChatTurnEvent struct {
	TurnID   string          `json:"turn_id"`
	Slug     string          `json:"slug"`
	Source   string          `json:"source"`
	Model    string          `json:"model"`
	Request  json.RawMessage `json:"request,omitempty"`  // populated for chat turns
	Kind     ChatTurnKind    `json:"kind,omitempty"`     // "" == chat
	Subagent *SubagentSpec   `json:"subagent,omitempty"` // populated when Kind=subagent
}

// ChatTurnKind discriminates ChatTurnEvent. Empty == chat. Core emits
// Kind=subagent only from SubagentService.RunBatch, the one producer
// of subagent runs.
type ChatTurnKind string

const (
	// ChatTurnKindChat is the parent's chat turn. Default; empty wire
	// value decodes to this so the agent runtime branch is "if
	// kind==subagent else chat".
	ChatTurnKindChat ChatTurnKind = ""

	// ChatTurnKindSubagent is a subagent run driven by
	// SubagentService. The agent pod runs it through its driver
	// (provider.Client.RunSubagent) and POSTs stream events back via the same chat-turn
	// event endpoint; core routes them to the subagent's chat.jsonl
	// instead of the parent's.
	ChatTurnKindSubagent ChatTurnKind = "subagent"
)

// SubagentSpec is the full set of inputs the agent pod needs to
// drive one subagent run. Carried inline on ChatTurnEvent.Subagent
// so a single round trip starts the run.
//
// SubagentSpec deliberately does NOT carry MCP server launch details
// — the agent pod builds the run's one MCP server itself (it knows
// its own Kivali binary path + UDS socket path). The spec carries the
// SubagentID the subagent's MCP needs to scope its file_* tools.
//
// Nothing in it is specific to a model provider: the pod turns it
// into a provider.SubagentRequest and the driver owns every flag, file
// format and tool-name spelling. Changing its shape is a core-to-pod
// wire change; core and pod are one binary and a deploy cycles every
// agent pod, so both sides always move together.
//
// Post docs/developers/files-and-publishing.md: no input refs on the wire. The
// subagent inherits a narrowed view of the parent's /files/ via a
// symlink overlay (see files.BuildSubagentOverlay), so any path the
// parent could file_view is already reachable from the prompt.
type SubagentSpec struct {
	// SubagentID is the per-call id allocated by core. Used by the
	// agent pod's subprocess working dir, the subagent's MCP
	// `--subagent-id` flag, and core's chat.jsonl routing
	// (agents/<parent>/subagents/<id>/chat.jsonl).
	SubagentID string `json:"subagent_id"`

	// Description is the parent's one-line task description. Surfaces
	// in the subagent's system prompt and in transcript rendering.
	Description string `json:"description,omitempty"`

	// Model is the model the subagent should run on (per-task override
	// from the parent's subagent tool input). Empty defaults to the
	// agent pod's configured subagent model.
	Model string `json:"model,omitempty"`

	// Effort is the subagent's reasoning level (an effort id). Per-task
	// override from the parent's subagent tool input; empty defaults to
	// the model's default effort at spawn time.
	Effort string `json:"effort,omitempty"`

	// SystemPrompt is the rendered system prompt the agent pod passes
	// to the driver as SubagentRequest.System. Built core-side via
	// SubagentSystemPrompt so the wording stays in lock-step with the
	// parent's understanding of the task.
	SystemPrompt string `json:"system_prompt"`

	// UserPrompt is the parent's user-prompt text: the run's one
	// prompt (SubagentRequest.Prompt).
	UserPrompt string `json:"user_prompt"`

	// Tools is the run's tool set in provider-neutral terms: the
	// kivali MCP server's tools by bare name and the provider-side
	// builtins by neutral id. Locked to SubagentTools(depth)
	// server-side; the pod hands it to provider.Client.RunSubagent and
	// the driver spells it the provider's way.
	//
	// Wire change: this replaced the comma-joined CLI flag strings
	// "allowed_tools" and "builtin_tools". Core and the pod are the same
	// binary and the deploy cycles every agent pod, so no pod ever reads
	// a spec of the other shape.
	Tools provider.ToolSet `json:"tools"`

	// Depth is how many tiers below the durable agent this subagent
	// sits: 1 for one the agent dispatched itself, 2 for a worker
	// dispatched by one of those. It decides which tools this
	// subagent's MCP child exposes and which delegation frame its
	// system prompt carries.
	//
	// Core computes it from the DISPATCHING job's registry entry and
	// locks it into the spec here. The agent pod passes it to the MCP
	// child but never lets a subagent's request set it — a subagent
	// that could name its own depth could name 0 and delegate forever.
	//
	// Zero on the wire means 1: specs written before depth existed
	// describe tier-1 subagents, and defaulting keeps an in-flight
	// deploy from spawning leaves that think they are sub-leads.
	Depth int `json:"depth,omitempty"`
}

// EffectiveDepth returns the spec's depth with the zero value mapped
// to tier 1. Callers should use this rather than the field directly.
func (s SubagentSpec) EffectiveDepth() int {
	if s.Depth < 1 {
		return 1
	}
	return s.Depth
}

// CancelTurnEvent is the payload core emits to ask the agent runtime
// to abort the in-flight chat turn. TurnID identifies which turn so
// a stale cancel arriving after the runtime already moved on is a
// safe no-op (no matching stream to cancel).
type CancelTurnEvent struct {
	TurnID string `json:"turn_id"`
	Slug   string `json:"slug"`
}

// CacheInvalidateEvent names cache keys the agent runtime should
// drop. Paths are Kivali-style /files/... view paths; SHAs reach
// content-addressed resources (project files, attachments).
// Either or both lists may be empty.
// FoldMessageEvent asks the runtime to splice Text into the turn named
// by TurnID, which core believes is in flight.
//
// DeliveryID is CORE's id for the buffered message. It comes back on
// the TurnEventFolded so core knows which of possibly several buffered
// deliveries the outcome refers to. The runner mints a separate uuid
// for the CLI's own queue; that one never leaves the pod, because core
// has no use for it and correlating on it would couple core to the
// CLI's wire format.
type FoldMessageEvent struct {
	TurnID     string `json:"turn_id"`
	Slug       string `json:"slug"`
	DeliveryID string `json:"delivery_id"`
	Text       string `json:"text"`
}

type CacheInvalidateEvent struct {
	Paths []string `json:"paths,omitempty"`
	SHAs  []string `json:"shas,omitempty"`
}

// SessionResetEvent names the agent whose warm CLI runner core wants
// torn down after a chat rotation. Slug is redundant with the pod's
// bound slug (one agent per pod) but carried explicitly so the runtime
// evicts the right registry key without reaching into the outbound
// client's private state.
type SessionResetEvent struct {
	Slug string `json:"slug"`
}

// PingEvent carries a server timestamp so a future ping-ack
// implementation can compute round-trip time. Payload-free in
// practice today.
type PingEvent struct {
	ServerTime string `json:"server_time"`
}

// Event is one decoded SSE frame off the events stream. Type names
// the kind; Data carries the raw JSON body for callers to unmarshal
// into the typed payload struct above (ChatTurnEvent, etc.). Keeping
// Data as []byte lets the consumer skip unmarshal entirely for event
// types it doesn't care about (forward-compat as we add events).
type Event struct {
	Type EventType
	Data []byte
}

// SlugHeader is the HTTP header name the agent client sets on every
// request (and the events stream open) so the server can verify
// slug identity matches the URL path. Mode 0700 socket file +
// matching UID is the auth boundary; this is belt-and-suspenders
// against a request being routed under the wrong slug due to a
// path-construction bug.
const SlugHeader = "X-Kivali-Agent"

// SlugFromHeader returns the caller's slug header.
func SlugFromHeader(h http.Header) string {
	return h.Get(SlugHeader)
}

// SocketName is the canonical filename of the agent-pod-facing UDS
// socket on the shared hostPath. Mode 0700 owned by the Kivali UID.
// Both core (listener) and the agent runtime (client) derive their
// path by joining the hostPath dir with this name; symmetry removes
// a class of "they disagreed on the path" failures.
const SocketName = "core.sock"

// TurnEventKind discriminates events the agent runtime POSTs back to
// core for one in-flight chat turn. The wire shape is JSON; core's
// handler dispatches based on this field.
//
// The first five mirror provider.StreamEventKind one-to-one: the agent
// runtime drives a CLI, observes stream events, and forwards them
// here so core can persist them to chat.jsonl + broadcast to the
// chat hub's SSE-to-browser path. The last two are agent-runtime
// concepts core needs to act on:
//
//   - TurnEventDone — the turn ran to completion. Carries usage
//     totals + stop reason. Core uses these to update telemetry +
//     emit the chat hub's "done" event.
//   - TurnEventFailed — something went wrong mid-turn that the
//     runtime can't recover from. Most importantly,
//     FailedReason="subprocess-died" is the resumption-bug carrier:
//     core writes a kind:runtime-disruption chat row on receipt
//     so SpawnDecision flips to SpawnNow on the next inbound
//     (parity with the in-process LoopExitSubprocessDied path,
//     see internal/agent/run_result.go).
type TurnEventKind string

const (
	TurnEventDelta          TurnEventKind = "delta"
	TurnEventThinking       TurnEventKind = "thinking"
	TurnEventToolUseStart   TurnEventKind = "tool_use_start"
	TurnEventToolUseEnd     TurnEventKind = "tool_use_end"
	TurnEventToolInputDelta TurnEventKind = "tool_input_delta"
	TurnEventToolResult     TurnEventKind = "tool_result"
	TurnEventDone           TurnEventKind = "done"
	TurnEventFailed         TurnEventKind = "failed"
	// TurnEventFolded reports the fate of one EventFoldMessage.
	// Landed=true means the running turn consumed the message and will
	// answer it in THIS turn, so core appends it to the transcript at
	// this point in the stream. Landed=false means it did not — the
	// runtime refused, or the turn ended before a fold seam came up —
	// and core delivers it the way it always has.
	//
	// Exactly one of these is posted per fold, and never both.
	TurnEventFolded TurnEventKind = "folded"
	// TurnEventError carries, in Text, the provider's account of a
	// model call that failed and ended the run (provider.StreamError).
	// It is never the agent speaking: core holds it as the detail of
	// the turn-error marker the done (StopReason provider.StopError)
	// that follows produces, and never files it as a reply.
	TurnEventError TurnEventKind = "error"
)

// TurnModelUsage is one model's share of a turn's tokens, carried on
// TurnEventDone so core can price each model at its own rate instead of
// billing a whole mixed turn at whichever id answered last.
type TurnModelUsage struct {
	Model             string `json:"model"`
	InputTokens       int    `json:"input_tokens,omitempty"`
	OutputTokens      int    `json:"output_tokens,omitempty"`
	CacheReadTokens   int    `json:"cache_read_tokens,omitempty"`
	CacheCreateTokens int    `json:"cache_create_tokens,omitempty"`
}

// TurnEvent is one event reported from the agent runtime to core for
// a specific in-flight chat turn. Path-scoped via
// /v1/agent/{slug}/chat-turn/{turn-id}/event so core can correlate
// events back to the originating PublishAgentpodEvent's TurnID.
//
// Field population per Kind:
//
//	delta              → Text
//	thinking           → Text (extended-reasoning chunk; live-only)
//	tool_use_start     → ToolUseID, ToolName
//	tool_input_delta   → ToolUseID, Text (partial JSON chunk)
//	tool_use_end       → ToolUseID, ToolName, ToolInput (full JSON)
//	tool_result        → ToolUseID, ToolResultText, ToolResultIsError
//	error              → Text (the failed model call's detail)
//	done               → StopReason, InputTokens, OutputTokens
//	failed             → FailedReason, FailedDetail
type TurnEvent struct {
	Kind TurnEventKind `json:"kind"`

	// TurnEventFolded payload. DeliveryID echoes the id core put on
	// the FoldMessageEvent; Landed says whether this turn took it.
	DeliveryID string `json:"delivery_id,omitempty"`
	Landed     bool   `json:"landed,omitempty"`

	// Stream-shape fields (mirror provider.StreamEvent).
	//
	// Model on a delta is the model that produced THAT text, read off
	// the CLI's assistant message. It arrives with the first delta
	// rather than waiting for Done because core labels each chat bubble
	// with the model that wrote it, and a turn can switch models between
	// calls — a value that only lands at the end would mislabel every
	// bubble the turn already flushed.
	Text              string `json:"text,omitempty"`
	ToolUseID         string `json:"tool_use_id,omitempty"`
	ToolName          string `json:"tool_name,omitempty"`
	ToolInput         []byte `json:"tool_input,omitempty"`
	ToolResultText    string `json:"tool_result_text,omitempty"`
	ToolResultIsError bool   `json:"tool_result_is_error,omitempty"`

	// Done payload. Cache token counts are forwarded so core's
	// usage_display formatting (provider.Client.FormatUsage) renders
	// identical numbers across in-process and UDS paths — a
	// difference here would surface as a sparkline jump for the
	// same-content turn.
	//
	// Model + CostUSD are populated on TurnEventDone so the
	// usage.jsonl rows core writes carry the model id the CLI reported
	// (some runs override the parent's model via SubagentSpec.Model)
	// and the CLI's own total_cost_usd when present (more accurate than
	// re-pricing from token counts when the transport reports a
	// discounted batch rate). Core falls back to Provider.Price if
	// CostUSD is zero.
	//
	// Model is the LAST model to answer, not the only one — see ByModel
	// below. It is the right label for a single-model turn and the wrong
	// basis for pricing a mixed one, because the flat counts accumulate
	// across every call in the turn.
	StopReason        string  `json:"stop_reason,omitempty"`
	InputTokens       int     `json:"input_tokens,omitempty"`
	OutputTokens      int     `json:"output_tokens,omitempty"`
	CacheReadTokens   int     `json:"cache_read_tokens,omitempty"`
	CacheCreateTokens int     `json:"cache_create_tokens,omitempty"`
	Model             string  `json:"model,omitempty"`
	CostUSD           float64 `json:"cost_usd,omitempty"`

	// ByModel splits the token counts above by the model that served
	// each call, in the order they answered. Present only when a turn
	// was actually served by more than one model; nil is the common
	// single-model case, where the flat fields already say it.
	//
	// The flat counts stay the true total whether or not this is set, so
	// a reader that ignores ByModel still sees the whole turn.
	ByModel []TurnModelUsage `json:"by_model,omitempty"`

	// ContextTokens is the window occupancy of the SINGLE last API call
	// of the turn (input + cache_read + cache_create off the final
	// assistant message), forwarded from
	// provider.CompleteResponse.ContextTokens. The token counts above
	// ACCUMULATE across a multi-step tool loop (they're a billing total);
	// this one does not — it's the real prompt size the model saw on its
	// last call, which is what the context-fill gauge needs. Feeding the
	// accumulated sum to the gauge would over-count by the number of
	// internal round-trips.
	ContextTokens int `json:"context_tokens,omitempty"`

	// Failed payload — the resumption-bug carrier.
	// FailedReason values:
	//   - "subprocess-died" — claude CLI subprocess exited mid-turn;
	//     core writes a KindRuntimeDisruption row and resumes the agent.
	//   - "other-error"     — generic transport failure; core writes a
	//     KindTurnError row and holds the agent.
	//   - "turn-error"      — the model call itself failed (the CLI
	//     closed the turn with is_error); same row and hold as above.
	//   - "cancelled"       — Stop; no row, the interruption marker
	//     was written at click time.
	FailedReason string `json:"failed_reason,omitempty"`
	FailedDetail string `json:"failed_detail,omitempty"`
}

const (
	// FailedReasonSubprocessDied marks a chat-turn-failed event as
	// the subprocess-death case — core writes KindRuntimeDisruption
	// on receipt. Stable string so future binaries on either side
	// can be deployed independently.
	FailedReasonSubprocessDied = "subprocess-died"

	// FailedReasonOtherError marks any other unrecoverable transport
	// or state failure mid-turn: the stream could not be opened, the
	// payload was malformed, the CLI answered with an error, or the
	// pod's SSE went away without a terminator. Core
	// writes KindTurnError and holds the agent until something new
	// arrives.
	FailedReasonOtherError = "other-error"

	// FailedReasonTurnError marks a turn the model call ended on an
	// error: the CLI closed it with a result frame carrying is_error
	// (a usage limit, an expired login, a 429, an output-token
	// maximum), which the driver reports as provider.StreamError events
	// and a final StopReason of provider.StopError. For a parent turn
	// core DERIVES this reason from a done event whose StopReason is
	// provider.StopError, with the TurnEventError texts as the detail; a
	// subagent run posts it directly, with FailedDetail holding the
	// error text, and core treats both spellings alike.
	FailedReasonTurnError = "turn-error"

	// FailedReasonCancelled marks the failure as a deliberate cancel
	// (Stop click, EventCancelTurn). Core's handler skips the
	// disruption-row write since the user-interruption marker (set
	// independently by handleAgentStop) is the right signal.
	FailedReasonCancelled = "cancelled"
)

// MemoryDispatchRequest is the JSON body of
// POST /v1/agent/{slug}/memory/dispatch. The agent pod's MCP
// agent_memory_* tool handlers route here instead of mutating
// agent_memory.md against a local FSStore (which doesn't exist on
// the agent pod — /data is core-only). Tool names match
// agent.AgentMemoryAppendToolName and agent.AgentMemoryStrReplaceToolName.
//
// One endpoint covers both ops, so a single round trip carries the full mutation including
// validation (str-replace uniqueness, etc.) under core's lock.
type MemoryDispatchRequest struct {
	Tool  string          `json:"tool"`
	Input json.RawMessage `json:"input"`
}

// MemoryDispatchResponse mirrors the agent.DispatchAgentMemoryTool
// return shape: Body is the rendered tool_result text; IsError is
// the tool-level failure flag (validation errors, str-replace
// uniqueness violations, etc.). Distinct from a transport error,
// which surfaces as non-2xx HTTP status.
type MemoryDispatchResponse struct {
	Body    string `json:"body,omitempty"`
	IsError bool   `json:"is_error,omitempty"`
}

// ShareFileDispatchRequest is the JSON body of
// POST /v1/agent/{slug}/share-file/dispatch. The agent pod's MCP
// share_file tool handler routes here so attachment resolution
// (agent.ResolveShareFilePath, which walks the agent's symlink
// farm) and the chat.jsonl append (Store.AppendChatMessage) both
// run against the authoritative core store under its lock.
//
// Field semantics match share_file's input schema: every entry in
// Files names a /files/... path the agent has access to, and they
// all land in a single chat bubble together. Caption is optional
// and applies to the whole bubble.
type ShareFileDispatchRequest struct {
	Files   []ShareFileEntry `json:"files"`
	Caption string           `json:"caption,omitempty"`
}

// ShareFileEntry is one file in a share_file batch: required Path,
// optional Name override (defaults to the path basename). Mirrors
// the entries in the input schema's `files` array.
type ShareFileEntry struct {
	Path string `json:"path"`
	Name string `json:"name,omitempty"`
}

// ShareFileDispatchResponse mirrors the rendered tool_result shape:
// Body is the model-visible ack string; IsError captures tool-level
// failure (resolve mismatch, append failure, etc.).
type ShareFileDispatchResponse struct {
	Body    string `json:"body,omitempty"`
	IsError bool   `json:"is_error,omitempty"`
}

// ArtifactDispatchRequest is the JSON body of
// POST /v1/agent/{slug}/artifact/dispatch: one artifact_publish or
// artifact_unpublish call, which core executes (it is the only writer
// of the published trees). SubagentID is set when a subagent calls:
// its client is bound to the parent's slug, and the id says which view
// of the parent's tree Source is a path in.
type ArtifactDispatchRequest struct {
	Tool       string `json:"tool"`
	SubagentID string `json:"subagent_id,omitempty"`
	Source     string `json:"source,omitempty"`
	Dest       string `json:"dest,omitempty"`
	Path       string `json:"path,omitempty"`
}

// ArtifactDispatchResponse is the rendered tool_result: Body for the
// model, IsError for a refused or failed call.
type ArtifactDispatchResponse struct {
	Body    string `json:"body,omitempty"`
	IsError bool   `json:"is_error,omitempty"`
}

// PublishStageRequest is the JSON body of
// POST /v1/agent/{slug}/publish/stage — phase 1 of the two-phase
// publish flow. The agent pod's MCP publish_* tool handlers (notice,
// ceo_approval_request, ceo_notification, the propose_* family) call
// stage first; on success
// they follow up with CommitPublish carrying the returned StageID.
//
// Stage runs the deterministic, non-durable prep work — parse,
// duplicate-role guard, attachment resolution — and persists a staged
// publish record to disk. NO message file is written and NO message
// queue mutation happens at stage time. Stage failures (parse error,
// role conflict, unreachable attachment) surface as IsError=true with
// no staging record created; bridge surfaces straight to the model
// without retry, because the inputs are deterministic.
//
// Tool names match message.ToolsFor's emitted definitions; Input is
// the raw tool arguments JSON the model produced.
type PublishStageRequest struct {
	Tool  string          `json:"tool"`
	Input json.RawMessage `json:"input"`
}

// PublishStageResponse is the response to /publish/stage.
//
// On success: StageID is the opaque identifier the bridge passes to
// /publish/commit; IsError is false; Body is empty (the rendered
// tool_result body is produced at commit time, not stage time, so it
// can reference the queue state observed under the commit lock).
//
// On failure: IsError is true; Body holds the rendered error string
// (model-visible); StageID is empty.
type PublishStageResponse struct {
	StageID string `json:"stage_id,omitempty"`
	Body    string `json:"body,omitempty"`
	IsError bool   `json:"is_error,omitempty"`
}

// PublishCommitRequest is the JSON body of
// POST /v1/agent/{slug}/publish/commit — phase 2 of the two-phase
// publish flow. The bridge sends the StageID returned by stage; the
// server reads the staged publish record, writes the message file at
// its deterministic path, and atomically updates message_queue.json
// (appending the recipient inbox entry AND recording stage_id in the
// queue's CommittedStageIDs set under one lock acquisition).
//
// Commit is idempotent on StageID: any number of retries with the
// same id yields the same Body / IsError. After a transport failure
// the bridge MAY retry commit safely; the server short-circuits on
// the second call because CommittedStageIDs already contains the id.
type PublishCommitRequest struct {
	StageID string `json:"stage_id"`
}

// PublishCommitResponse is the response to /publish/commit. Body is
// the rendered tool_result body; IsError flags tool-level failure
// (route warnings ride on Body with IsError=false, matching the
// in-process behavior — persistence succeeded, route is best-effort).
//
// Distinguishing absences:
//
//   - HTTP 404 / "stage_id not found" — the bridge should NOT
//     interpret this as success; the staged record is missing
//     (expired by janitor, or a stale bridge talking to a fresh
//     core after data wipe). Re-stage and try again.
//   - HTTP 5xx — transport-class failure; retry on the same StageID
//     is safe.
type PublishCommitResponse struct {
	Body    string `json:"body,omitempty"`
	IsError bool   `json:"is_error,omitempty"`
}

// StateDispatchRequest is the JSON body of
// POST /v1/agent/{slug}/state/dispatch. The agent pod's MCP state-
// tools (get_org_chart, list_skills, read_agent_role, the graph reads
// and the assignment tools) all funnel through this one endpoint
// — the server runs the existing rendering logic against the
// authoritative store and returns the model-visible body. Mirrors
// the MemoryDispatch pattern.
//
// Tool-name validation lives server-side; unknown names surface as
// IsError on the response body, not a transport error.
type StateDispatchRequest struct {
	Tool  string          `json:"tool"`
	Input json.RawMessage `json:"input,omitempty"`
}

// StateDispatchResponse mirrors the rendered tool_result envelope:
// Body is the model-visible string, IsError flags tool-level
// failure (CoS-only gate violation, redact target not pending,
// unknown tool, etc.).
type StateDispatchResponse struct {
	Body    string `json:"body,omitempty"`
	IsError bool   `json:"is_error,omitempty"`
}
